/** 
 * 倪海厦三纪知识库 — 天纪/人纪/地纪
 * 纯浏览器 JavaScript — 依赖 window.Ziwei (ziwei-engine.js)
 * 基于倪海厦《天纪》(1994)《人纪》(2004-2005)《地纪》(未竟)
 */
(function() {
  'use strict';
  if (typeof window.Ziwei === 'undefined') {
    console.error('[Ziwei Nihai] 需先加载 ziwei-engine.js');
    return;
  }

/**
 * 天纪 — 倪海厦天文术数体系数据库
 *
 * 「上知天文」—— 天之纪，是术数研究的体系化成果。
 * 1994年录制，共24集视频（每集2小时，共48小时）。
 * 讲义分为《天机道》《人间道》《地脉道》《64卦易图》四册。
 *
 * 核心学派：
 *   紫微斗数 → 三合派
 *   风水     → 九星派（杨救贫流派）
 *   易经     → 象数派
 *   推命     → 河洛数理派
 */

// ─── 天纪模块 ────────────────────────────────────────────
const TIANJI_MODULES= [
  {
    id: 'tj-ziwei',
    category: 'tianji',
    name: '紫微斗数',
    nameEn: 'Zi Wei Dou Shu',
    subtitle: '三合派 · 倪师正宗体系',
    description: '以紫微星为主轴，十四主星配十二宫位，结合四化星推演人生格局。倪师主张「大道至简」，不用飞星派复杂化法，以三合派为正宗。',
    details: [
      '紫微斗数是倪师天纪课程的核心命学工具，属三合派体系。倪师明言：「飞星（四化）飞来飞去太复杂，不搞这个，毕竟大道至简。」',
      '课程以十二张案例讲义为教材，紫微星在十二个位置各一张，从子宫到亥宫绕一圈，覆盖所有主星排列。',
      '倪师强调命宫为本、三方为用——命宫主星决定基本格局与天生性格，三方（财帛、官禄、迁移）决定用武之地。',
      '四化星（化禄、化权、化科、化忌）的运用是核心技法，配合大限流年推演人生关键节点。',
    ],
    school: '三合派',
    lessons: '天纪视频前半部分（约24小时）',
    references: [
      '《紫微斗数全集》',
      '《紫微斗数全书》',
      '《骨髓赋》',
      '倪海厦《天纪》讲义（天机道篇）',
    ],
    keywords: ['紫微斗数', '三合派', '十四主星', '十二宫位', '四化星', '大限', '流年', '命宫', '三方四正', '格局'],
    icon: '◉',
    status: 'active',
    order: 1,
    slug: 'ziwei',
    chapters: [
      {
        id: 'tj-zw-01',
        title: '紫微斗数基础',
        subtitle: '安星法与排盘原理',
        description: '从年支排盘入手，了解紫微斗数的基本安星规则、十二宫位的含义与相互关系。',
        keyPoints: [
          '以年支排盘，非子平法的年柱排列',
          '十二宫位：命宫、兄弟、夫妻、子女、财帛、疾厄、迁移、交友、官禄、田宅、福德、父母',
          '命宫为一切分析的起点',
          '身宫可看影响最重的宫位',
        ],
        quotes: ['身宫在财帛宫的女孩子，一般来说就是职业妇女'],
        order: 1,
      },
      {
        id: 'tj-zw-02',
        title: '十四主星详解',
        subtitle: '星性与庙旺利陷',
        description: '深入讲解紫微、天机、太阳、武曲、天同、廉贞、天府、太阴、贪狼、巨门、天相、天梁、七杀、破军十四颗主星的性质。',
        keyPoints: [
          '每颗主星有独特的性格特质与命理意涵',
          '亮度系统（庙/旺/得/利/平/不/陷）影响星力发挥',
          '杀破狼三星一定同在三方，构成变动格局',
          '紫微星为帝座，天府为财库',
        ],
        quotes: ['最怕的是七杀临身，七杀临身的人一辈子多败少成'],
        order: 2,
      },
      {
        id: 'tj-zw-03',
        title: '四化星运用',
        subtitle: '化禄化权化科化忌',
        description: '四化星是紫微斗数的灵魂技法，每年天干对应四颗星化入不同宫位，推动命运变化。',
        keyPoints: [
          '化禄星主财，性守——代表财运和享受',
          '化权星性刚，代表官印——代表权力和掌控',
          '化科星主科名，名气很大——代表名声和贵人',
          '化忌星主劫杀——代表阻碍和困难',
          '大限四化与流年四化叠加判断',
        ],
        order: 3,
      },
      {
        id: 'tj-zw-04',
        title: '格局与断命',
        subtitle: '经典格局与实战案例',
        description: '从杀破狼、火贪格等经典格局入手，结合倪师十二张案例讲义实战断命。',
        keyPoints: [
          '官禄宫最喜欢权星入进来',
          '杀破狼格局代表变动与开创',
          '火贪格主暴发',
          '命相同参可提高准确率',
          '结合面相（五形论）辅助判断',
        ],
        order: 4,
      },
    ],
  },
  {
    id: 'tj-yijing',
    category: 'tianji',
    name: '易经六十四卦',
    nameEn: 'Yi Jing 64 Hexagrams',
    subtitle: '象数派 · 断易天机',
    description: '倪师以《断易天机》为底本，自创图示法讲解六十四卦，前一小时讲命学，后一小时讲易经，相辅相成。',
    details: [
      '易经部分以象数派为主，倪师自行演变的易图是独特教学工具，极大简化了学习难度。',
      '64卦图解底本来自《断易天机》，倪师重新排列、注解，形成独有的图示教学法。',
      '课程不仅教卦理，更注重实际占卜应用：如何起卦、解卦、断事。',
      '倪师强调易经不仅是占卜工具，更是决策智慧——「不但看到时机，还能马上做决策」。',
    ],
    school: '象数派',
    lessons: '天纪视频后半部分（约24小时）',
    references: [
      '《断易天机》',
      '《周易》',
      '倪海厦《人间道·64卦易图》',
    ],
    keywords: ['易经', '六十四卦', '八卦', '象数派', '占卜', '断易天机', '图示法', '六爻'],
    icon: '☰',
    status: 'active',
    order: 2,
    slug: 'yijing',
    chapters: [
      {
        id: 'tj-yj-01',
        title: '易经基础与八卦',
        subtitle: '阴阳与先后天八卦',
        description: '从太极生两仪、两仪生四象、四象生八卦入手，建立易经的基础知识体系。',
        keyPoints: [
          '乾（天）、兑（泽）、离（火）、震（雷）、巽（风）、坎（水）、艮（山）、坤（地）',
          '先天八卦与后天八卦的区别',
          '八卦的象征意义与自然对应',
          '六爻的由来与结构',
        ],
        order: 1,
      },
      {
        id: 'tj-yj-02',
        title: '六十四卦详解',
        subtitle: '图示法与卦辞解读',
        description: '逐卦讲解六十四卦的卦象、卦辞、爻辞要义，配合倪师独创图示法。',
        keyPoints: [
          '每卦由上下两个三爻卦叠合而成',
          '卦辞揭示整体趋势，爻辞指示具体位置',
          '变卦（动爻）是断事的关键',
          '倪师图解简化了传统解卦的复杂性',
        ],
        order: 2,
      },
      {
        id: 'tj-yj-03',
        title: '占卜实战',
        subtitle: '起卦与断事方法',
        description: '从起卦方法到断事技巧，覆盖完整的占卜实战流程。',
        keyPoints: [
          '多种起卦法：揲蓍法、金钱卦、梅花易数等',
          '用神取用与六亲关系',
          '六神（青龙、朱雀、勾陈、腾蛇、白虎、玄武）占断',
          '时间、方位、事态的综合判断',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'tj-kanyu',
    category: 'tianji',
    name: '堪舆学',
    nameEn: 'Kan Yu Xue',
    subtitle: '九星派 · 杨救贫流派',
    description: '涵盖阳宅风水与阴宅选择，以九星派（杨救贫流派）为正宗，讲解三吉六秀、八煞黄泉等核心风水理论。',
    details: [
      '堪舆学是天纪课程「下知地理」的核心板块，属于《地脉道》讲义内容。',
      '倪师采用杨救贫九星派体系，强调峦头（山形水势）与理气（方位吉凶）并重。',
      '阳宅部分讲解居住环境对人生的影响，包括房屋朝向、内部布局、周围环境等。',
      '阴宅部分讲解墓地选择与立向，强调「八煞黄泉」是绝对禁忌的方位。',
      '倪师认为「人事的努力加上地理上的调整，一定能大于先天的命运」，即2/3大于1/3的核心理念。',
    ],
    school: '九星派（杨救贫流派）',
    lessons: '天纪视频第18-21集',
    references: [
      '倪海厦《地脉道》讲义',
      '杨救贫风水典籍',
    ],
    keywords: ['堪舆', '风水', '阳宅', '阴宅', '九星派', '杨救贫', '八煞黄泉', '三吉六秀', '峦头', '理气'],
    icon: '⊞',
    status: 'active',
    order: 3,
    slug: 'kanyu',
    chapters: [
      {
        id: 'tj-ky-01',
        title: '阳宅风水',
        subtitle: '居住环境与人生运势',
        description: '讲解住宅选择与布局的风水原理，包括朝向、格局、周围环境对居住者的影响。',
        keyPoints: [
          '三吉方向（生气、延年、天医）与六秀方向的概念',
          '房屋坐向与居住者八字的配合',
          '室内布局：厨房、卧室、书房的方位选择',
          '居住位置、睡眠方向对人生轨迹的影响',
        ],
        order: 1,
      },
      {
        id: 'tj-ky-02',
        title: '阴宅风水',
        subtitle: '墓地选择与立向',
        description: '讲解墓地选址的峦头理论与立向禁忌，强调八煞黄泉等绝对禁忌。',
        keyPoints: [
          '八煞黄泉：坟墓和阳宅立向的绝对禁忌',
          '天星四贵的概念与应用',
          '龙穴砂水的基本判断',
          '城局与九星的配合',
        ],
        order: 2,
      },
      {
        id: 'tj-ky-03',
        title: '风水与命运',
        subtitle: '地理调整改善运势',
        description: '倪师关于风水与命运关系的核心理论——人事努力+地理调整>先天命运。',
        keyPoints: [
          '2/3大于1/3理论：人事努力+地理=2/3，先天命运=1/3',
          '好的风水地方要有鱼虾龟（生气充沛的标志）',
          '来龙、朝山、砂势的综合判断',
          '结合紫微斗数的田宅宫来看风水需求',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'tj-tuiming',
    category: 'tianji',
    name: '推命学',
    nameEn: 'Tui Ming Xue',
    subtitle: '河洛数理派 · 子平法',
    description: '以子平法排列的易经推命术，结合河洛数理派理论，是紫微斗数之外的另一套命学工具。',
    details: [
      '推命学在天纪中作为紫微斗数的补充命学工具出现。',
      '倪师介绍了两种命学体系：一是子平法排列的八字推命术，二是紫微斗数用年支排盘的方式。',
      '河洛数理派注重数字与五行的对应关系，从数理角度分析命运轨迹。',
      '倪师建议学生应同时掌握多种命学工具，以便交叉验证、提高准确度。',
    ],
    school: '河洛数理派',
    lessons: '天纪课程穿插讲解',
    references: [
      '《子平真诠》',
      '《河洛数理》',
    ],
    keywords: ['推命', '八字', '子平法', '河洛数理', '四柱', '五行', '天干地支'],
    icon: '⊡',
    status: 'preview',
    order: 4,
    slug: 'tuiming',
    chapters: [
      {
        id: 'tj-tm-01',
        title: '四柱八字基础',
        subtitle: '天干地支与五行',
        description: '子平法的基础知识，包括天干地支的五行属性、十神关系、大运流年的排列。',
        keyPoints: [
          '十天干与十二地支的五行属性',
          '年柱、月柱、日柱、时柱的排列',
          '十神体系与六亲关系',
          '大运排列与流年推演',
        ],
        order: 1,
      },
    ],
  },
  {
    id: 'tj-mianxiang',
    category: 'tianji',
    name: '面相学',
    nameEn: 'Mian Xiang Xue',
    subtitle: '五形论 · 命相同参',
    description: '面相学是天纪课程中辅助命理判断的重要工具，倪师强调「命相同参会提高准确率」。',
    details: [
      '面相学以「五形论」为核心——木、火、土、金、水五种面相类型。',
      '倪师强调五形的「纯正性」决定贵贱：越纯正的面相类型越贵。',
      '特殊贵相的识别：「南人北相、北人南相」是贵相的重要标志。',
      '面相不是孤立判断，必须结合紫微斗数的命盘分析，做到「命相同参」。',
    ],
    school: '五形面相',
    lessons: '天纪课程穿插讲解',
    references: [
      '《麻衣相法》',
      '《神相全编》',
    ],
    keywords: ['面相', '五形论', '木火土金水', '命相同参', '南人北相', '气色'],
    icon: '⊙',
    status: 'preview',
    order: 5,
    slug: 'mianxiang',
    chapters: [
      {
        id: 'tj-mx-01',
        title: '五形论基础',
        subtitle: '木火土金水面相分类',
        description: '五种基本面相类型的特征识别与贵贱判断。',
        keyPoints: [
          '木形人：身材高瘦，面长色青',
          '火形人：面尖上阔，色红气急',
          '土形人：面圆肉厚，色黄声重',
          '金形人：面方骨正，色白声清',
          '水形人：面圆肉浮，色黑性柔',
        ],
        order: 1,
      },
    ],
  },
  {
    id: 'tj-cezi',
    category: 'tianji',
    name: '测字术',
    nameEn: 'Ce Zi Shu',
    subtitle: '拆字法 · 会意法',
    description: '测字是中国传统占卜术之一，通过分析文字的笔画、结构、含义来推断吉凶。',
    details: [
      '测字术在天纪课程中作为辅助占卜手段出现。',
      '主要方法包括拆字法（分解字形）和会意法（联想字义）。',
      '倪师认为测字的准确性取决于测者的悟性和经验积累。',
    ],
    school: '传统测字',
    lessons: '天纪课程穿插讲解',
    references: [
      '《拆字辞典》',
    ],
    keywords: ['测字', '拆字法', '会意法', '占卜'],
    icon: '⊚',
    status: 'coming',
    order: 6,
    slug: 'cezi',
    chapters: [
      {
        id: 'tj-cz-01',
        title: '测字基础',
        subtitle: '拆字与会意',
        description: '测字术的基本方法与实战技巧。',
        keyPoints: [
          '拆字法：将文字拆解为偏旁部首分别解读',
          '会意法：根据文字含义联想推断',
          '时间与环境因素的结合',
        ],
        order: 1,
      },
    ],
  },
];

// ─── 易经六十四卦数据库 ──────────────────────────────────
const HEXAGRAMS= [
  { number: 1, name: '乾', composition: '乾为天', upper: '乾', lower: '乾', meaning: '元亨利贞，天行健，君子以自强不息', niInterpretation: '纯阳之卦，刚健中正，至大至刚', divination: '大吉大利，但需注意亢龙有悔' },
  { number: 2, name: '坤', composition: '坤为地', upper: '坤', lower: '坤', meaning: '元亨，利牝马之贞，地势坤，君子以厚德载物', niInterpretation: '纯阴之卦，柔顺承载', divination: '宜顺从，不宜主动' },
  { number: 3, name: '屯', composition: '水雷屯', upper: '坎', lower: '震', meaning: '元亨利贞，勿用有攸往', niInterpretation: '万物初生之象，创业维艰', divination: '初创时期，宜守不宜进' },
  { number: 4, name: '蒙', composition: '山水蒙', upper: '艮', lower: '坎', meaning: '亨，匪我求童蒙，童蒙求我', niInterpretation: '启蒙教育之卦，需有耐心', divination: '求学问道有利，需虚心受教' },
  { number: 5, name: '需', composition: '水天需', upper: '坎', lower: '乾', meaning: '有孚，光亨贞吉，利涉大川', niInterpretation: '等待时机之卦，需要耐心', divination: '宜等待时机成熟再行动' },
  { number: 6, name: '讼', composition: '天水讼', upper: '乾', lower: '坎', meaning: '有孚窒惕，中吉终凶', niInterpretation: '争讼之卦，不宜争斗', divination: '争讼不利，宜和解退让' },
  { number: 7, name: '师', composition: '地水师', upper: '坤', lower: '坎', meaning: '贞丈人吉，无咎', niInterpretation: '统兵之卦，需正义之师', divination: '行事需有正当名分' },
  { number: 8, name: '比', composition: '水地比', upper: '坎', lower: '坤', meaning: '吉，原筮元永贞，无咎', niInterpretation: '亲附比辅之卦，团结互助', divination: '宜寻求合作与结盟' },
  { number: 9, name: '小畜', composition: '风天小畜', upper: '巽', lower: '乾', meaning: '亨，密云不雨，自我西郊', niInterpretation: '小有积蓄之卦，力量不足以大成', divination: '小事可成，大事尚需等待' },
  { number: 10, name: '履', composition: '天泽履', upper: '乾', lower: '兑', meaning: '履虎尾，不咥人，亨', niInterpretation: '行事谨慎之卦，如履虎尾', divination: '小心谨慎可化险为夷' },
  { number: 11, name: '泰', composition: '地天泰', upper: '坤', lower: '乾', meaning: '小往大来，吉亨', niInterpretation: '天地交泰，通达之象', divination: '万事亨通，大吉' },
  { number: 12, name: '否', composition: '天地否', upper: '乾', lower: '坤', meaning: '否之匪人，不利君子贞', niInterpretation: '天地不交，闭塞之象', divination: '诸事不顺，宜守待时' },
  { number: 13, name: '同人', composition: '天火同人', upper: '乾', lower: '离', meaning: '同人于野，亨，利涉大川', niInterpretation: '志同道合之卦', divination: '合作共事有利' },
  { number: 14, name: '大有', composition: '火天大有', upper: '离', lower: '乾', meaning: '元亨', niInterpretation: '大丰收之卦，光明正大', divination: '事业丰盛，大有所获' },
  { number: 15, name: '谦', composition: '地山谦', upper: '坤', lower: '艮', meaning: '亨，君子有终', niInterpretation: '谦逊之卦，唯一六爻皆吉之卦', divination: '谦虚谨慎，诸事吉利' },
  { number: 16, name: '豫', composition: '雷地豫', upper: '震', lower: '坤', meaning: '利建侯行师', niInterpretation: '安乐和豫之卦，但不可过度', divination: '可有所作为，但勿过于安逸' },
  { number: 17, name: '随', composition: '泽雷随', upper: '兑', lower: '震', meaning: '元亨利贞，无咎', niInterpretation: '随顺之卦，择善而从', divination: '随机应变，顺势而行' },
  { number: 18, name: '蛊', composition: '山风蛊', upper: '艮', lower: '巽', meaning: '元亨，利涉大川', niInterpretation: '整治积弊之卦，拨乱反正', divination: '需要整顿改革' },
  { number: 19, name: '临', composition: '地泽临', upper: '坤', lower: '兑', meaning: '元亨利贞，至于八月有凶', niInterpretation: '亲临监督之卦，居高临下', divination: '可有所作为，但注意时效' },
  { number: 20, name: '观', composition: '风地观', upper: '巽', lower: '坤', meaning: '盥而不荐，有孚颙若', niInterpretation: '观察审视之卦，以下观上', divination: '宜观察形势，不宜冒进' },
  { number: 21, name: '噬嗑', composition: '火雷噬嗑', upper: '离', lower: '震', meaning: '亨，利用狱', niInterpretation: '刑罚决断之卦，去除障碍', divination: '果断处理障碍，排除困难' },
  { number: 22, name: '贲', composition: '山火贲', upper: '艮', lower: '离', meaning: '亨，小利有攸往', niInterpretation: '文饰之卦，外在修饰', divination: '注重外表形式，小事可成' },
  { number: 23, name: '剥', composition: '山地剥', upper: '艮', lower: '坤', meaning: '不利有攸往', niInterpretation: '剥落衰败之卦', divination: '不宜行动，宜守静待变' },
  { number: 24, name: '复', composition: '地雷复', upper: '坤', lower: '震', meaning: '亨，出入无疾，朋来无咎', niInterpretation: '一阳来复之卦，否极泰来', divination: '转机出现，渐入佳境' },
  { number: 25, name: '无妄', composition: '天雷无妄', upper: '乾', lower: '震', meaning: '元亨利贞', niInterpretation: '无妄之灾亦需坦然面对', divination: '正道而行可吉，妄动则凶' },
  { number: 26, name: '大畜', composition: '山天大畜', upper: '艮', lower: '乾', meaning: '利贞，不家食吉，利涉大川', niInterpretation: '大有积蓄之卦，厚积薄发', divination: '积累实力，蓄势待发' },
  { number: 27, name: '颐', composition: '山雷颐', upper: '艮', lower: '震', meaning: '贞吉，观颐，自求口实', niInterpretation: '养生颐养之卦', divination: '注意饮食养生，自力更生' },
  { number: 28, name: '大过', composition: '泽风大过', upper: '兑', lower: '巽', meaning: '栋桡，利有攸往，亨', niInterpretation: '阳气过盛之卦，过犹不及', divination: '事情过度，需要调整' },
  { number: 29, name: '坎', composition: '坎为水', upper: '坎', lower: '坎', meaning: '习坎，有孚，维心亨', niInterpretation: '重重险难之卦，但心诚可亨', divination: '困难重重，但坚守信念可过关' },
  { number: 30, name: '离', composition: '离为火', upper: '离', lower: '离', meaning: '利贞，亨，畜牝牛吉', niInterpretation: '光明附丽之卦，文明之象', divination: '宜守正道，光明正大' },
  { number: 31, name: '咸', composition: '泽山咸', upper: '兑', lower: '艮', meaning: '亨利贞，取女吉', niInterpretation: '感应之卦，男女相感', divination: '感情婚姻大吉' },
  { number: 32, name: '恒', composition: '雷风恒', upper: '震', lower: '巽', meaning: '亨，无咎利贞，利有攸往', niInterpretation: '恒久不变之卦，持之以恒', divination: '坚持不懈可成功' },
  { number: 33, name: '遁', composition: '天山遁', upper: '乾', lower: '艮', meaning: '亨，小利贞', niInterpretation: '退隐之卦，适时退避', divination: '宜退不宜进，暂避锋芒' },
  { number: 34, name: '大壮', composition: '雷天大壮', upper: '震', lower: '乾', meaning: '利贞', niInterpretation: '刚强壮盛之卦，但壮不可妄动', divination: '力量充沛，但需守正' },
  { number: 35, name: '晋', composition: '火地晋', upper: '离', lower: '坤', meaning: '康侯用锡马蕃庶', niInterpretation: '日出地上之卦，步步高升', divination: '事业晋升，前途光明' },
  { number: 36, name: '明夷', composition: '地火明夷', upper: '坤', lower: '离', meaning: '利艰贞', niInterpretation: '光明损伤之卦，韬光养晦', divination: '宜隐藏光芒，低调行事' },
  { number: 37, name: '家人', composition: '风火家人', upper: '巽', lower: '离', meaning: '利女贞', niInterpretation: '家庭和睦之卦', divination: '家庭事务吉利' },
  { number: 38, name: '睽', composition: '火泽睽', upper: '离', lower: '兑', meaning: '小事吉', niInterpretation: '背离分歧之卦，求同存异', divination: '小事可成，大事不宜' },
  { number: 39, name: '蹇', composition: '水山蹇', upper: '坎', lower: '艮', meaning: '利西南，不利东北', niInterpretation: '行路艰难之卦', divination: '前路困难，宜结伴同行' },
  { number: 40, name: '解', composition: '雷水解', upper: '震', lower: '坎', meaning: '利西南，无所往', niInterpretation: '解除困难之卦，雨过天晴', divination: '困难解除，宜速行事' },
  { number: 41, name: '损', composition: '山泽损', upper: '艮', lower: '兑', meaning: '有孚，元吉，无咎', niInterpretation: '损下益上之卦，适当牺牲', divination: '有所舍才有所得' },
  { number: 42, name: '益', composition: '风雷益', upper: '巽', lower: '震', meaning: '利有攸往，利涉大川', niInterpretation: '损上益下之卦，有利可图', divination: '事业有益，宜大胆行动' },
  { number: 43, name: '夬', composition: '泽天夬', upper: '兑', lower: '乾', meaning: '扬于王庭', niInterpretation: '决断之卦，以阳决阴', divination: '需果断处理，不可犹豫' },
  { number: 44, name: '姤', composition: '天风姤', upper: '乾', lower: '巽', meaning: '女壮，勿用取女', niInterpretation: '相遇之卦，一阴初生', divination: '偶然相遇，不宜深交' },
  { number: 45, name: '萃', composition: '泽地萃', upper: '兑', lower: '坤', meaning: '亨，王假有庙', niInterpretation: '聚集之卦，众志成城', divination: '聚集力量，团结协作' },
  { number: 46, name: '升', composition: '地风升', upper: '坤', lower: '巽', meaning: '元亨，用见大人', niInterpretation: '上升之卦，步步高升', divination: '事业上升，宜见贵人' },
  { number: 47, name: '困', composition: '泽水困', upper: '兑', lower: '坎', meaning: '亨贞，大人吉，无咎', niInterpretation: '困顿之卦，但大人可吉', divination: '身处困境，守正可渡' },
  { number: 48, name: '井', composition: '水风井', upper: '坎', lower: '巽', meaning: '改邑不改井', niInterpretation: '水井之卦，不变中的恒常', divination: '固守根本，不可轻易改变' },
  { number: 49, name: '革', composition: '泽火革', upper: '兑', lower: '离', meaning: '己日乃孚', niInterpretation: '变革之卦，革故鼎新', divination: '时机成熟可变革' },
  { number: 50, name: '鼎', composition: '火风鼎', upper: '离', lower: '巽', meaning: '元吉，亨', niInterpretation: '鼎新之卦，建立新制', divination: '事业更新，大吉' },
  { number: 51, name: '震', composition: '震为雷', upper: '震', lower: '震', meaning: '亨，震来虩虩', niInterpretation: '震动之卦，初惊后安', divination: '先有惊扰，后可安定' },
  { number: 52, name: '艮', composition: '艮为山', upper: '艮', lower: '艮', meaning: '艮其背，不获其身', niInterpretation: '止静之卦，适可而止', divination: '宜停止观望，不宜冒进' },
  { number: 53, name: '渐', composition: '风山渐', upper: '巽', lower: '艮', meaning: '女归吉，利贞', niInterpretation: '循序渐进之卦', divination: '宜循序渐进，不可操之过急' },
  { number: 54, name: '归妹', composition: '雷泽归妹', upper: '震', lower: '兑', meaning: '征凶，无攸利', niInterpretation: '少女出嫁之卦，位置不正', divination: '感情事宜需谨慎' },
  { number: 55, name: '丰', composition: '雷火丰', upper: '震', lower: '离', meaning: '亨，王假之', niInterpretation: '丰盛之卦，日中则昃', divination: '盛极必衰，宜居安思危' },
  { number: 56, name: '旅', composition: '火山旅', upper: '离', lower: '艮', meaning: '小亨，旅贞吉', niInterpretation: '旅行在外之卦', divination: '旅行出行小吉，需谨慎' },
  { number: 57, name: '巽', composition: '巽为风', upper: '巽', lower: '巽', meaning: '小亨，利有攸往', niInterpretation: '顺从之卦，柔顺渗透', divination: '宜顺势而为，不宜强行' },
  { number: 58, name: '兑', composition: '兑为泽', upper: '兑', lower: '兑', meaning: '亨利贞', niInterpretation: '喜悦之卦，和悦相处', divination: '和乐融融，社交有利' },
  { number: 59, name: '涣', composition: '风水涣', upper: '巽', lower: '坎', meaning: '亨，王假有庙', niInterpretation: '涣散之卦，化解分散', divination: '团队涣散，需凝聚人心' },
  { number: 60, name: '节', composition: '水泽节', upper: '坎', lower: '兑', meaning: '亨，苦节不可贞', niInterpretation: '节制之卦，适度为宜', divination: '凡事需节制，过犹不及' },
  { number: 61, name: '中孚', composition: '风泽中孚', upper: '巽', lower: '兑', meaning: '豚鱼吉，利涉大川', niInterpretation: '诚信之卦，至诚感通', divination: '诚信待人，可成大事' },
  { number: 62, name: '小过', composition: '雷山小过', upper: '震', lower: '艮', meaning: '亨利贞，可小事不可大事', niInterpretation: '小有过越之卦', divination: '小事可为，大事不宜' },
  { number: 63, name: '既济', composition: '水火既济', upper: '坎', lower: '离', meaning: '亨小，利贞，初吉终乱', niInterpretation: '事已成就之卦，但需谨防衰败', divination: '事情已成，但需注意善后' },
  { number: 64, name: '未济', composition: '火水未济', upper: '离', lower: '坎', meaning: '亨，小狐汔济，濡其尾', niInterpretation: '尚未完成之卦，事在人为', divination: '事未完成，需继续努力' },
];

// ─── 堪舆学条目 ──────────────────────────────────────────
const FENGSHUI_ENTRIES= [
  {
    id: 'fs-bashayq',
    title: '八煞黄泉',
    category: 'theory',
    description: '立向的绝对禁忌，坟墓和阳宅都不可犯。八煞黄泉是风水学中最严重的忌讳之一。',
    keyPoints: ['坟墓和阳宅立向使用', '绝对不能立的向', '犯之主大凶'],
  },
  {
    id: 'fs-sanjilx',
    title: '三吉六秀',
    category: 'yangzhai',
    description: '阳宅风水中的吉利方位。三吉方向（生气、延年、天医）代表最佳的方位选择。',
    keyPoints: ['三吉：生气、延年、天医', '六秀方向有好的砂势则吉', '有山势、来龙、朝山为佳'],
  },
  {
    id: 'fs-tianxsg',
    title: '天星四贵',
    category: 'yinzhai',
    description: '阴宅选址的高级技法，用于判断墓地周围的贵气方位。',
    keyPoints: ['天星方位判断贵气', '与龙穴砂水配合使用', '九星派核心理论之一'],
  },
  {
    id: 'fs-yangzhai',
    title: '阳宅布局',
    category: 'yangzhai',
    description: '居住环境的风水布局原则，包括房屋坐向、室内格局、周围环境的综合考量。',
    keyPoints: ['房屋坐向需配合居住者', '厨房方位影响家人健康', '卧室位置影响夫妻感情', '居住位置与睡眠方向影响运势'],
  },
  {
    id: 'fs-longxueshashui',
    title: '龙穴砂水',
    category: 'yinzhai',
    description: '风水四大要素——龙脉走势、穴位选择、砂的环抱、水的流向，构成完整的风水格局。',
    keyPoints: ['龙：山脉走势与来龙', '穴：藏风聚气的最佳位置', '砂：穴位周围的山势环抱', '水：水流走向与聚散'],
  },
  {
    id: 'fs-chengjujiuxing',
    title: '城局与九星',
    category: 'theory',
    description: '杨救贫九星派的核心理论，通过九星的排列组合判断风水格局的吉凶。',
    keyPoints: ['九星：贪巨禄文廉武破左右', '城局形势的整体判断', '与天星四贵配合使用'],
  },
];

// ─── 天纪24集课程结构（每集2小时：前半段命学/后半段易经） ──
const TIANJI_EPISODES= [
  { dvd: 1, firstHalf: '天纪开篇·天纪与真理', secondHalf: '易经三义·先后天八卦', highlights: ['如何分辨君子与小人', '天地人三才论', '紫微斗数为何优于子平法', '文字只是船真理才是彼岸'] },
  { dvd: 2, firstHalf: '紫微斗数·十二宫位详解', secondHalf: '八卦地理配置·爻变与时机', highlights: ['命宫为本三方为用', '夫妻宫兼看福德宫', '面相五形论', '名位相等原则', '卜筮有时机不疑何卜'] },
  { dvd: 3, firstHalf: '紫微斗数·星辰介绍(上)', secondHalf: '乾坤屯蒙需讼', highlights: ['紫微星帝座特质', '天府财库星', '太阳星庙旺利陷', '天机善星智慧'] },
  { dvd: 4, firstHalf: '紫微斗数·星辰介绍(下)', secondHalf: '师比小畜履泰否', highlights: ['杀破狼三星一定同在三方', '武曲财星', '贪狼桃花星', '廉贞囚星', '巨门暗星'] },
  { dvd: 5, firstHalf: '紫微斗数·十二张案例讲义', secondHalf: '同人大有谦豫随蛊', highlights: ['十二张案例紫微在十二宫各一张', '命宫贪狼文武双全', '身宫在财帛宫为职业妇女', '阳宅化解论'] },
  { dvd: 6, firstHalf: '紫微斗数·四化星详解', secondHalf: '临观噬嗑贲剥复', highlights: ['化禄主财性守', '化权性刚代表官印', '化科主科名名气', '化忌主劫杀', '大限流年四化叠加'] },
  { dvd: 7, firstHalf: '紫微斗数·格局论(上)', secondHalf: '无妄大畜颐大过坎离', highlights: ['杀破狼格局变动开创', '火贪格主暴发', '三方四正看格局', '官禄宫最喜权星'] },
  { dvd: 8, firstHalf: '紫微斗数·格局论(下)', secondHalf: '咸恒遁大壮晋明夷', highlights: ['流年批命法', '迷津评断一生总格局', '命相同参提高准确率', '南人北相为贵相'] },
  { dvd: 9, firstHalf: '紫微斗数·大限流年', secondHalf: '家人睽蹇解损益', highlights: ['大限十年运势', '小限流年推算', '人定胜天论', '三年前化解论'] },
  { dvd: 10, firstHalf: '紫微斗数·实战案例(上)', secondHalf: '夬姤萃升困井', highlights: ['官禄化忌事业受阻', '财帛化禄财运亨通', '夫妻宫煞星婚姻不顺'] },
  { dvd: 11, firstHalf: '紫微斗数·实战案例(下)', secondHalf: '革鼎震艮渐归妹', highlights: ['疾厄宫判断健康', '结合中医子午流注', '煞星在午主心脏在丑主肝'] },
  { dvd: 12, firstHalf: '面相学·五形论详解', secondHalf: '丰旅巽兑涣节', highlights: ['木火土金水五种面相类型', '越纯越贵原则', '气色主两个礼拜', '眼神判断法'] },
  { dvd: 13, firstHalf: '面相学·气色与断命', secondHalf: '中孚小过既济未济', highlights: ['面相气色判断吉凶', '印堂日角月角', '眉毛代表六亲', '眼袋判断子女'] },
  { dvd: 14, firstHalf: '推命学·子平法入门', secondHalf: '64卦综合应用(上)', highlights: ['子平法四柱八字排列', '天干地支五行属性', '十神体系'] },
  { dvd: 15, firstHalf: '推命学·大运流年', secondHalf: '64卦综合应用(下)', highlights: ['大运排列', '流年推演', '卦象在实际生活中的应用'] },
  { dvd: 16, firstHalf: '测字术·拆字会意法', secondHalf: '占卜实战·起卦法', highlights: ['拆字法分解偏旁', '会意法联想推断', '揲蓍法', '金钱卦'] },
  { dvd: 17, firstHalf: '测字术·实战案例', secondHalf: '六爻断事技巧', highlights: ['测字时机和环境', '六神占断', '用神取用'] },
  { dvd: 18, firstHalf: '堪舆学·峦头论(上)', secondHalf: '龙穴砂水基础', highlights: ['山形水势判断', '龙脉走势与气脉', '穴位藏风聚气'] },
  { dvd: 19, firstHalf: '堪舆学·峦头论(下)', secondHalf: '罗盘使用与理气', highlights: ['砂手环抱', '水口进出', '罗盘方位测量', '九星飞布原理'] },
  { dvd: 20, firstHalf: '堪舆学·阳宅风水', secondHalf: '三吉六秀·天星四贵', highlights: ['房屋坐向选择', '室内方位安排', '三吉方向', '六秀方向好砂则吉'] },
  { dvd: 21, firstHalf: '堪舆学·阴宅风水', secondHalf: '八煞黄泉·城局九星', highlights: ['八煞黄泉绝对禁忌', '天星四贵', '城局形势判断', '来龙朝山砂势'] },
  { dvd: 22, firstHalf: '堪舆学·2/3大于1/3', secondHalf: '风水改运实例', highlights: ['人事+地理=2/3>天命1/3', '好风水有鱼虾龟', '床位朝向决定生子性别'] },
  { dvd: 23, firstHalf: '综合应用·命相卜术结合', secondHalf: '天纪在生活中的实践', highlights: ['紫微+面相+易经综合判断', '天地人三纪统一观', '倪师批命实战示范'] },
  { dvd: 24, firstHalf: '天纪总结·核心心法', secondHalf: '传承与期许', highlights: ['天纪精神总结', '命运掌握在自己手上', '文化传承使命', '不希望中华文化失传'] },
];

// ─── 倪师天纪核心语录库 ──────────────────────────────────
const TIANJI_QUOTES = [
  { text: '文字只是协助诸位到达真理的彼岸，千万不要三个月以后，怎么还是扛着船在马路上跑', topic: '学习态度' },
  { text: '大道至简——飞星飞来飞去太复杂，不搞这个', topic: '紫微斗数' },
  { text: '命宫为本，三方为用——命宫主星决定基本格局与天生性格，三方决定用武之地', topic: '紫微斗数' },
  { text: '身宫在财帛宫的女孩子，一般来说就是职业妇女', topic: '紫微斗数' },
  { text: '最怕的是七杀临身，七杀临身的人一辈子多败少成', topic: '紫微斗数' },
  { text: '官禄宫最喜欢权星入进来', topic: '紫微斗数' },
  { text: '算命就是一个讨论果的哲学', topic: '命学哲理' },
  { text: '命是天注定的，运掌握在我们自己手上', topic: '命学哲理' },
  { text: '三年前有办法化解，到了时候再改都是事后。碗打破了我们再去解', topic: '命学哲理' },
  { text: '祸福无门，咎由自取', topic: '命学哲理' },
  { text: '看到外面，就知道里面藏了什么', topic: '面相' },
  { text: '看相最难看的就是气色。气色主两个礼拜', topic: '面相' },
  { text: '越纯越贵——五形越纯正的面相类型越贵', topic: '面相' },
  { text: '南人北相、北人南相是贵相的重要标志', topic: '面相' },
  { text: '害的到你的叫做小人。会影响到你的叫做小人', topic: '识人' },
  { text: '眼珠闪动主心术不正，四白眼主横死，三角眼主心生毒计', topic: '面相' },
  { text: '人事的努力加上地理上的调整，一定能大于先天的命运', topic: '堪舆' },
  { text: '好的风水地方要有鱼虾龟——生气充沛的标志', topic: '堪舆' },
  { text: '八煞黄泉是坟墓和阳宅立向的绝对禁忌', topic: '堪舆' },
  { text: '唯有紫微斗数可以把天文和地理两个融合在一起', topic: '紫微斗数' },
  { text: '如果读了易经，越弄越复杂，就是没有读通易经', topic: '易经' },
  { text: '不疑何卜——只有有疑虑时才占卜', topic: '易经' },
  { text: '外象一直在变，但精神是一样的', topic: '易经' },
  { text: '爸爸住爸爸位置，儿子住儿子位置，叫做名位相等', topic: '堪舆' },
  { text: '中国五百年出一个天官，现在还不到五百年', topic: '天文' },
  { text: '煞星通过疾厄宫在午主心脏，在丑主肝', topic: '紫微斗数' },
  { text: '我不希望这些中华文化失传，所以就教了许多学生', topic: '传承' },
  { text: '命相同参会提高准确率', topic: '综合' },
  { text: '天纪就是自然法则，是真理', topic: '天纪总论' },
];

// ─── 统计 ────────────────────────────────────────────────
const TIANJI_STATS = {
  totalModules: TIANJI_MODULES.length,
  activeModules: TIANJI_MODULES.filter(m => m.status === 'active').length,
  totalChapters: TIANJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  totalHexagrams: HEXAGRAMS.length,
  totalFengShui: FENGSHUI_ENTRIES.length,
  totalEpisodes: TIANJI_EPISODES.length,
  totalQuotes: 29,
  videoHours: 48,
  videoEpisodes: 24,
  hdEpisodes: 83,
  recordYear: 1994,
  lectureBooks: ['天机道', '人间道', '地脉道', '64卦易图'],
  schools: ['三合派（紫微斗数）', '象数派（易经）', '九星派（堪舆）', '河洛数理派（推命）'],
};

/**
 * 人纪 — 倪海厦中医经典教学体系数据库
 *
 * 「中知人事」—— 人之纪，是中医经典的体系化教学。
 * 2004-2005年完成，包含五大中医经典课程。
 * 学习顺序：针灸 → 黄帝内经 → 神农本草经 → 伤寒论 → 金匮要略
 *
 * 核心理念：
 *   中医是物理医学，从物理的角度分析人的身体。
 *   学成者可从感冒治疗至肝癌。
 */

// ─── 人纪模块 ────────────────────────────────────────────
const RENJI_MODULES= [
  {
    id: 'rj-zhenjiu',
    category: 'renji',
    name: '针灸大成',
    nameEn: 'Zhen Jiu Da Cheng',
    subtitle: '人纪第一课 · 经络穴位',
    description: '针灸是人纪的入门课程，依据《针灸甲乙经》和《针灸大成》讲授。通过经络穴位的学习，建立对人体气血运行的基本认知。',
    details: [
      '针灸课是人纪系列的第一门课，也是中医入门的基础。倪师强调，不懂经络穴位就无法理解中医的诊断与治疗。',
      '课程依据《针灸甲乙经》和《针灸大成》两部经典编写，系统讲解十二正经、奇经八脉的循行路线与主要穴位。',
      '倪师的针灸教学注重实战，每个穴位都有具体的临床应用说明，而非纯粹的理论记忆。',
      '倪师认为针灸是「最快速的治疗手段」，许多急症可以通过针灸迅速缓解。',
    ],
    lessons: '44集（每集约44分钟）',
    references: [
      '《针灸甲乙经》',
      '《针灸大成》',
      '倪海厦《人纪·针灸》讲义',
    ],
    keywords: ['针灸', '经络', '穴位', '十二正经', '奇经八脉', '针灸大成', '针灸甲乙经'],
    icon: '⊕',
    status: 'active',
    order: 1,
    slug: 'zhenjiu',
    chapters: [
      {
        id: 'rj-zj-01',
        title: '经络总论',
        subtitle: '十二正经与奇经八脉',
        description: '人体经络系统的整体框架，十二正经的循行路线与奇经八脉的特殊功能。',
        keyPoints: [
          '十二正经：手三阴、手三阳、足三阴、足三阳',
          '奇经八脉：任、督、冲、带、阴维、阳维、阴跷、阳跷',
          '经络的气血流注时间（子午流注）',
          '经络与脏腑的表里关系',
        ],
        order: 1,
      },
      {
        id: 'rj-zj-02',
        title: '重要穴位详解',
        subtitle: '临床常用穴位与配伍',
        description: '临床最常用的穴位定位、取穴方法与针刺技巧，以及常见病症的穴位配伍。',
        keyPoints: [
          '五输穴（井荥输经合）的运用',
          '原穴、络穴、俞穴、募穴的区别',
          '特殊穴位：百会、合谷、足三里、三阴交等',
          '补泻手法：提插补泻、捻转补泻',
        ],
        order: 2,
      },
      {
        id: 'rj-zj-03',
        title: '针灸治疗实战',
        subtitle: '常见病症的针灸方案',
        description: '从头痛到腰痛，从感冒到失眠，覆盖常见病症的针灸治疗方案。',
        keyPoints: [
          '头痛：不同经络的头痛对应不同穴位',
          '腰痛：委中、肾俞、大肠俞的运用',
          '急症：中风急救的针灸方法',
          '内科：失眠、消化不良、月经不调等',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-neijing',
    category: 'renji',
    name: '黄帝内经',
    nameEn: 'Huang Di Nei Jing',
    subtitle: '人纪第二课 · 中医理论根基',
    description: '《黄帝内经》是中医的理论根基，倪师通过讲解《素问》和《灵枢》，建立完整的中医哲学与诊断体系。',
    details: [
      '《黄帝内经》分为《素问》和《灵枢》两部分，是中医理论的最高经典。',
      '倪师的讲解不是逐字翻译，而是将古文智慧转化为可操作的临床知识。',
      '核心内容包括阴阳五行理论、脏腑学说、病因病机、诊断方法等。',
      '倪师特别强调「形神合一」的概念——中医不仅治病，更关注整体生命状态。',
    ],
    lessons: '20集（每集约1小时）',
    references: [
      '《黄帝内经·素问》',
      '《黄帝内经·灵枢》',
      '倪海厦《人纪·黄帝内经》讲义',
    ],
    keywords: ['黄帝内经', '素问', '灵枢', '阴阳', '五行', '脏腑', '病因病机', '形神'],
    icon: '☯',
    status: 'active',
    order: 2,
    slug: 'neijing',
    chapters: [
      {
        id: 'rj-nj-01',
        title: '阴阳五行',
        subtitle: '中医哲学基础',
        description: '阴阳对立统一与五行生克制化的基本理论，是理解中医一切诊断治疗的基础。',
        keyPoints: [
          '阴阳的基本特征与相互关系',
          '五行（木火土金水）的生克关系',
          '五行与脏腑的对应：肝木、心火、脾土、肺金、肾水',
          '五行在诊断和治疗中的应用',
        ],
        order: 1,
      },
      {
        id: 'rj-nj-02',
        title: '脏腑学说',
        subtitle: '五脏六腑的功能与关系',
        description: '五脏（肝心脾肺肾）和六腑（胆小肠胃大肠膀胱三焦）的生理功能与相互关系。',
        keyPoints: [
          '五脏藏精气、六腑传化水谷',
          '脏腑表里关系：肝胆、心小肠、脾胃等',
          '气血津液的生成与运行',
          '脏腑失调的病理表现',
        ],
        order: 2,
      },
      {
        id: 'rj-nj-03',
        title: '诊断方法',
        subtitle: '望闻问切四诊',
        description: '中医四诊——望（观察）、闻（听闻）、问（询问）、切（脉诊）的具体方法。',
        keyPoints: [
          '望诊：面色、舌象、形体、神态',
          '闻诊：声音、气味的辨别',
          '问诊：寒热、汗、疼痛、二便等',
          '切诊：脉象的基本分类与诊断意义',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-bencao',
    category: 'renji',
    name: '神农本草经',
    nameEn: 'Shen Nong Ben Cao Jing',
    subtitle: '人纪第三课 · 药物学根基',
    description: '《神农本草经》是中药学的鼻祖，倪师按上中下三品分类讲解365味药物的性味归经与临床运用。',
    details: [
      '《神农本草经》将药物分为上品（养命）、中品（养性）、下品（治病）三类。',
      '倪师的讲解重点在于每味药的核心功效和临床实际运用，而非死记硬背。',
      '课程特别强调「药有真假」——如何辨别药材的真伪和质量。',
      '倪师认为掌握本草经是开方用药的根基，没有这个基础，伤寒论和金匮的方剂就无法灵活运用。',
    ],
    lessons: '46集（每集约1小时）',
    references: [
      '《神农本草经》',
      '倪海厦《人纪·神农本草经》讲义',
    ],
    keywords: ['神农本草经', '中药', '本草', '上品', '中品', '下品', '性味归经', '药性'],
    icon: '⚘',
    status: 'active',
    order: 3,
    slug: 'bencao',
    chapters: [
      {
        id: 'rj-bc-01',
        title: '上品药物',
        subtitle: '养命延年 · 无毒',
        description: '上品120味，主养命以应天，无毒，多服久服不伤人。',
        keyPoints: [
          '人参：大补元气，生津止渴',
          '黄芪：补气固表，利水消肿',
          '甘草：调和诸药，补中益气',
          '上品药可作为日常调养之用',
        ],
        order: 1,
      },
      {
        id: 'rj-bc-02',
        title: '中品药物',
        subtitle: '养性补虚 · 有毒无毒',
        description: '中品120味，主养性以应人，无毒有毒，斟酌其宜。',
        keyPoints: [
          '当归：补血活血，调经止痛',
          '黄芩：清热燥湿，泻火解毒',
          '白术：健脾益气，燥湿利水',
          '中品药需要根据病情斟酌使用',
        ],
        order: 2,
      },
      {
        id: 'rj-bc-03',
        title: '下品药物',
        subtitle: '治病祛邪 · 有毒',
        description: '下品125味，主治病以应地，多毒不可久服。',
        keyPoints: [
          '附子：回阳救逆，大热',
          '大黄：泻下攻积，清热泻火',
          '巴豆：峻下冷积，有大毒',
          '下品药针对性强，需谨慎使用',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-shanghan',
    category: 'renji',
    name: '伤寒论',
    nameEn: 'Shang Han Lun',
    subtitle: '人纪第四课 · 辨证论治典范',
    description: '张仲景《伤寒论》是中医辨证论治的典范之作，倪师逐条讲解六经辨证体系与经方运用。',
    details: [
      '《伤寒论》以六经（太阳、阳明、少阳、太阴、少阴、厥阴）辨证为纲，系统阐述外感病的诊治。',
      '倪师的讲解注重临床实用性，每一条文都结合实际病例说明。',
      '经方（张仲景的方剂）是中医临床的核心武器，倪师强调「经方一剂知，二剂已」的神效。',
      '倪师认为伤寒论不仅治外感，更是治疗一切疾病的方法论基础。',
    ],
    lessons: '伤寒论原版DVD（每集约2小时）',
    references: [
      '《伤寒论》（张仲景）',
      '倪海厦《人纪·伤寒论》讲义',
    ],
    keywords: ['伤寒论', '张仲景', '六经辨证', '经方', '太阳病', '阳明病', '少阳病', '桂枝汤', '麻黄汤'],
    icon: '⚕',
    status: 'active',
    order: 4,
    slug: 'shanghan',
    chapters: [
      {
        id: 'rj-sh-01',
        title: '六经辨证总论',
        subtitle: '太阳阳明少阳太阴少阴厥阴',
        description: '六经辨证是伤寒论的核心框架，将一切外感病按六经归类，指导治疗方向。',
        keyPoints: [
          '太阳病：恶寒发热，头痛项强——表证',
          '阳明病：壮热汗出，大渴大烦——里实热证',
          '少阳病：往来寒热，胸胁苦满——半表半里',
          '太阴病：腹满而吐，食不下——里虚寒证',
          '少阴病：脉微细，但欲寐——阳虚寒化或阴虚热化',
          '厥阴病：消渴，气上撞心——寒热错杂',
        ],
        order: 1,
      },
      {
        id: 'rj-sh-02',
        title: '核心经方',
        subtitle: '桂枝汤、麻黄汤等经典方剂',
        description: '伤寒论中最重要的方剂，每一首方都有明确的适应症和使用条件。',
        keyPoints: [
          '桂枝汤：调和营卫，太阳中风第一方',
          '麻黄汤：发汗解表，太阳伤寒第一方',
          '小柴胡汤：和解少阳，柴胡证的主方',
          '白虎汤：清阳明里热',
          '四逆汤：回阳救逆，少阴寒化的主方',
        ],
        order: 2,
      },
      {
        id: 'rj-sh-03',
        title: '方证辨析',
        subtitle: '同病异治与异病同治',
        description: '通过伤寒论的条文学习辨证论治的精髓——同一疾病可用不同方剂，不同疾病可用同一方剂。',
        keyPoints: [
          '辨证而非辨病：看的是证型而非病名',
          '方证对应：每个方剂有其特定的适应症候群',
          '经方加减：根据兼证灵活加减',
          '传经与变证的判断',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-jingui',
    category: 'renji',
    name: '金匮要略',
    nameEn: 'Jin Gui Yao Lue',
    subtitle: '人纪第五课 · 杂病诊治大成',
    description: '张仲景《金匮要略》是中医杂病治疗的最高经典，倪师讲解各种内科杂病的辨证论治方法。',
    details: [
      '《金匮要略》是《伤寒杂病论》的杂病部分，与《伤寒论》互为补充。',
      '伤寒论主治外感，金匮主治内伤杂病——两者合起来就是张仲景的完整临床体系。',
      '倪师的讲解涵盖痰饮、水气、黄疸、妇人病等各类杂病的诊治。',
      '金匮是人纪最后一门课，需要前四门课的知识基础才能理解运用。',
    ],
    lessons: '20集（每集约1小时）',
    references: [
      '《金匮要略》（张仲景）',
      '倪海厦《人纪·金匮要略》讲义',
    ],
    keywords: ['金匮要略', '张仲景', '杂病', '痰饮', '水气', '黄疸', '妇人病', '经方'],
    icon: '⚗',
    status: 'active',
    order: 5,
    slug: 'jingui',
    chapters: [
      {
        id: 'rj-jg-01',
        title: '杂病总论',
        subtitle: '病因病机与治则',
        description: '杂病的发病原因、病理机制与治疗原则的总论。',
        keyPoints: [
          '内伤杂病与外感病的区别',
          '五脏风寒的辨证方法',
          '虚实寒热的鉴别要点',
          '治未病的预防思想',
        ],
        order: 1,
      },
      {
        id: 'rj-jg-02',
        title: '痰饮水气',
        subtitle: '痰饮四类与水肿治法',
        description: '痰饮、悬饮、溢饮、支饮四种痰饮病的辨证论治，以及水气病的治疗。',
        keyPoints: [
          '痰饮四类的鉴别',
          '水气病（风水、皮水、正水、石水）',
          '苓桂术甘汤：痰饮病的基础方',
          '五苓散：水气病的常用方',
        ],
        order: 2,
      },
      {
        id: 'rj-jg-03',
        title: '妇人病与杂病各论',
        subtitle: '妇科与各科杂病',
        description: '妇人妊娠病、产后病、杂病以及其他各科杂病的辨证论治。',
        keyPoints: [
          '妇人妊娠病的治疗原则',
          '产后三大病（痉、郁冒、大便难）',
          '黄疸的辨证分型与治疗',
          '胸痹（胸痛）的治疗方剂',
        ],
        order: 3,
      },
    ],
  },
];

// ─── 215条针灸经验穴位（倪师临床精华） ────────────────────
const ACU_EXPERIENCES= [
  // 01 心·心血管系统
  { id: 1, condition: '冠心病', acupoints: '关元、巨阙、少府、涌泉、公孙', category: '心血管' },
  { id: 2, condition: '心脏肥大', acupoints: '巨阙、少府、神门、劳宫、关元、公孙、内关、天突', category: '心血管' },
  { id: 3, condition: '心绞痛', acupoints: '厉兑、人中、十宣（放血）、涌泉、百会（放血）', category: '心血管' },
  { id: 4, condition: '真心痛', acupoints: '巨阙、关元、天突、厉兑', category: '心血管' },
  { id: 5, condition: '心律不齐', acupoints: '关元、太渊', category: '心血管' },
  { id: 6, condition: '心悸', acupoints: '神门、少府、关元', category: '心血管' },
  { id: 7, condition: '心脏痛', acupoints: '公孙、内关、巨阙、关元、天突、厉兑', category: '心血管' },
  // 02 肝胆系统
  { id: 8, condition: '肝病', acupoints: '肝关、行间', category: '肝胆' },
  { id: 9, condition: '肝炎', acupoints: '行间', category: '肝胆' },
  { id: 10, condition: '肝硬化', acupoints: '肝俞、行间', category: '肝胆' },
  { id: 11, condition: '肝硬化腹水', acupoints: '水分、水道、肝关', category: '肝胆' },
  { id: 12, condition: '黄疸', acupoints: '脊中、行间', category: '肝胆' },
  { id: 13, condition: '胆结石', acupoints: '肝俞、胆俞、阳陵泉正下约一寸处（胆石点）', category: '肝胆' },
  // 03 脾胃消化系统
  { id: 14, condition: '胃病胃痛', acupoints: '中脘（梅花灸）、关元、天枢、公孙、内关', category: '脾胃' },
  { id: 15, condition: '胃癌', acupoints: '膺窗、鱼际、足三里、天溪、痞根、地五会', category: '脾胃' },
  { id: 16, condition: '腹痛', acupoints: '三阴交、公孙、关元、中极、肠关', category: '脾胃' },
  { id: 17, condition: '腹胀', acupoints: '水分（灸）、公孙、消积', category: '脾胃' },
  { id: 18, condition: '胃酸过多', acupoints: '公孙、内关', category: '脾胃' },
  { id: 19, condition: '消化不良', acupoints: '公孙、内关、腹通谷', category: '脾胃' },
  { id: 20, condition: '呕吐', acupoints: '公孙、内关、中脘、胃俞', category: '脾胃' },
  { id: 21, condition: '恶心反胃', acupoints: '中脘、公孙', category: '脾胃' },
  { id: 22, condition: '腹泻', acupoints: '天枢、大横、肠关、四满', category: '脾胃' },
  { id: 23, condition: '便秘', acupoints: '支沟、照海', category: '脾胃' },
  { id: 24, condition: '痔疮', acupoints: '长强、孔最、秩边、承山', category: '脾胃' },
  { id: 25, condition: '便血', acupoints: '下髎', category: '脾胃' },
  { id: 26, condition: '结直肠癌', acupoints: '痞根、消积', category: '脾胃' },
  { id: 27, condition: '结核性肠炎', acupoints: '神阙（灸）、温溜', category: '脾胃' },
  { id: 28, condition: '阑尾炎', acupoints: '阑尾、天枢、中脘、关元、足三里、肘尖（灸）', category: '脾胃' },
  { id: 29, condition: '疝气', acupoints: '隐白、肝俞、大敦（对侧）、行间', category: '脾胃' },
  { id: 30, condition: '水肿', acupoints: '水分、三阴交、地机、阴陵泉、水道', category: '脾胃' },
  // 04 肺·呼吸系统
  { id: 31, condition: '肺癌', acupoints: '中府、云门、孔最、公孙、内关', category: '肺系' },
  { id: 32, condition: '气喘', acupoints: '膻中、中府、云门、孔最、公孙、内关', category: '肺系' },
  { id: 33, condition: '咳嗽', acupoints: '太渊、灵墟、俞府、彧中', category: '肺系' },
  { id: 34, condition: '多痰', acupoints: '丰隆', category: '肺系' },
  { id: 35, condition: '鼻子不通', acupoints: '迎香、合谷（对侧）、通天', category: '肺系' },
  { id: 36, condition: '喉哑失声', acupoints: '哑门（禁灸）', category: '肺系' },
  { id: 37, condition: '胸中瘀血', acupoints: '巨骨', category: '肺系' },
  { id: 38, condition: '肺结核', acupoints: '肺俞、胆俞、膈俞', category: '肺系' },
  { id: 39, condition: '肺积水', acupoints: '膈俞、膻中、鸠尾、阳谷、后溪、照海、水分、水道、大包', category: '肺系' },
  // 05 肾·泌尿系统
  { id: 40, condition: '肾虚', acupoints: '肾俞、京门、命门', category: '肾系' },
  { id: 41, condition: '遗精', acupoints: '三阴交（灸）、横骨', category: '肾系' },
  { id: 42, condition: '前列腺肥大', acupoints: '阴陵泉、关元、足三里', category: '肾系' },
  { id: 43, condition: '阳强阳挺', acupoints: '蠡沟、曲泉', category: '肾系' },
  { id: 44, condition: '阴茎痛小腹痛', acupoints: '列缺、三阴交、次髎、大敦、行间', category: '肾系' },
  { id: 45, condition: '阴缩', acupoints: '大赫、大敦、行间', category: '肾系' },
  { id: 46, condition: '生殖器病', acupoints: '大敦', category: '肾系' },
  { id: 47, condition: '阴痛', acupoints: '少府', category: '肾系' },
  { id: 48, condition: '小便不利', acupoints: '中极、关元、三阴交、大钟、阴包', category: '肾系' },
  { id: 49, condition: '小便痛', acupoints: '大敦、阴包', category: '肾系' },
  { id: 50, condition: '尿频', acupoints: '中极、关元、阴陵泉', category: '肾系' },
  { id: 51, condition: '尿失禁', acupoints: '阴陵泉', category: '肾系' },
  { id: 52, condition: '肾结石', acupoints: '肾俞、京门、命门、交信和太溪之间（肾石点）', category: '肾系' },
  // 06 妇科·儿科
  { id: 53, condition: '痛经', acupoints: '关元（灸）、中极（灸）、三阴交、血海', category: '妇科' },
  { id: 54, condition: '月经过少', acupoints: '血海（血海下一寸针）', category: '妇科' },
  { id: 55, condition: '月经过多', acupoints: '隐白、行间', category: '妇科' },
  { id: 56, condition: '崩漏', acupoints: '隐白、交信、行间', category: '妇科' },
  { id: 57, condition: '赤白带下', acupoints: '隐白、次髎、阴谷、大赫、白环俞', category: '妇科' },
  { id: 58, condition: '子宫肌瘤', acupoints: '下巨虚、地机、三阴交', category: '妇科' },
  { id: 59, condition: '子宫下垂', acupoints: '交信、大敦', category: '妇科' },
  { id: 60, condition: '阴道痉挛', acupoints: '大敦', category: '妇科' },
  { id: 61, condition: '阴道痒', acupoints: '曲泉', category: '妇科' },
  { id: 62, condition: '阴唇痒', acupoints: '阴交（灸）', category: '妇科' },
  { id: 63, condition: '不孕症', acupoints: '关元（灸）、气冲、中极、上髎（灸）', category: '妇科' },
  { id: 64, condition: '孕吐', acupoints: '中脘、公孙', category: '妇科' },
  { id: 65, condition: '胎位不正', acupoints: '至阴', category: '妇科' },
  { id: 66, condition: '难产', acupoints: '支沟', category: '妇科' },
  { id: 67, condition: '胎盘不下', acupoints: '昆仑、太溪', category: '妇科' },
  { id: 68, condition: '产后恶露', acupoints: '中都', category: '妇科' },
  { id: 69, condition: '退乳断奶', acupoints: '陷谷、上巨虚', category: '妇科' },
  { id: 70, condition: '乳房疼痛', acupoints: '神封、内庭', category: '妇科' },
  { id: 71, condition: '乳房肿胀', acupoints: '上巨虚、内庭', category: '妇科' },
  { id: 72, condition: '乳炎乳瘫', acupoints: '内庭', category: '妇科' },
  { id: 73, condition: '乳腺小叶增生', acupoints: '上巨虚、天溪、地五会', category: '妇科' },
  { id: 74, condition: '乳房纤维瘤', acupoints: '天溪、地五会', category: '妇科' },
  { id: 75, condition: '乳腺癌', acupoints: '肩井、膺窗、鱼际、足三里、天溪、痞根、地五会', category: '妇科' },
  // 07 神志·神经
  { id: 76, condition: '脑血栓', acupoints: '百会', category: '神志', note: '无昏迷时用' },
  { id: 77, condition: '中风', acupoints: '百会、风府', category: '神志' },
  { id: 78, condition: '中风中经络', acupoints: '风市、阳陵泉、阴陵泉、悬钟、三阴交', category: '神志' },
  { id: 79, condition: '半身不遂', acupoints: '环跳、风市、阴市、悬钟', category: '神志' },
  { id: 80, condition: '周期性瘫痪', acupoints: '风市、阴市', category: '神志' },
  { id: 81, condition: '失眠', acupoints: '三毛（灸）、神门', category: '神志' },
  { id: 82, condition: '癫痫', acupoints: '申脉（灸）、照海（灸）、鸠尾、百会、人中、涌泉', category: '神志' },
  { id: 83, condition: '脑震荡', acupoints: '然谷（放血）', category: '神志' },
  { id: 84, condition: '红斑狼疮', acupoints: '心俞、肺俞、肝俞', category: '神志' },
  { id: 85, condition: '痴呆', acupoints: '悬钟、痞根', category: '神志' },
  { id: 86, condition: '肋间神经痛', acupoints: '肝关', category: '神志' },
  { id: 87, condition: '癫狂', acupoints: '筋缩', category: '神志' },
  { id: 88, condition: '脑瘤', acupoints: '百会、涌泉', category: '神志' },
  // 08 伤痛外科
  { id: 89, condition: '颈椎病', acupoints: '昆仑、后溪、申脉', category: '伤科' },
  { id: 90, condition: '头项强重', acupoints: '后溪、申脉、大杼、昆仑', category: '伤科' },
  { id: 91, condition: '落枕', acupoints: '手三里', category: '伤科' },
  { id: 92, condition: '五十肩', acupoints: '偏历、条口、承山、曲池、二间', category: '伤科' },
  { id: 93, condition: '肩膀酸痛', acupoints: '肩中俞、肩外俞、曲池、肩井、足三里', category: '伤科' },
  { id: 94, condition: '肩拉伤', acupoints: '肩井、足三里', category: '伤科' },
  { id: 95, condition: '网球肘', acupoints: '曲池（拔罐放血）、手三里', category: '伤科' },
  { id: 96, condition: '手指痛', acupoints: '合谷透劳宫、三间透后溪', category: '伤科' },
  { id: 97, condition: '腰痛', acupoints: '委中、肾俞、大肠俞', category: '伤科' },
  { id: 98, condition: '坐骨神经痛', acupoints: '环跳、阳陵泉、委中、悬钟', category: '伤科' },
  { id: 99, condition: '膝痛', acupoints: '风市、阴市、膝阳关透曲泉', category: '伤科' },
  { id: 100, condition: '脚扭伤', acupoints: '商丘透丘墟', category: '伤科', note: '一针见效' },
  // 09 五官科
  { id: 101, condition: '头痛（前额）', acupoints: '合谷、阳白', category: '五官' },
  { id: 102, condition: '头痛（偏头）', acupoints: '太阳透率谷、丝竹空（放血）', category: '五官' },
  { id: 103, condition: '头痛（后脑）', acupoints: '后溪、申脉、昆仑', category: '五官' },
  { id: 104, condition: '头痛（头顶）', acupoints: '陷谷透涌泉', category: '五官' },
  { id: 105, condition: '面瘫', acupoints: '阳白透鱼腰、地仓透颊车、丝竹空透太阳', category: '五官' },
  { id: 106, condition: '白内障', acupoints: '阳白透鱼腰、睛明、球后、承泣、养老', category: '五官' },
  { id: 107, condition: '近视眼', acupoints: '阳白透鱼腰、翳风、丘墟', category: '五官' },
  { id: 108, condition: '色盲', acupoints: '臂臑透肩髃、复溜、睛明、光明', category: '五官' },
  { id: 109, condition: '耳鸣', acupoints: '耳门、听宫、听会、肾俞、翳风', category: '五官' },
  { id: 110, condition: '牙痛', acupoints: '合谷、颊车、下关', category: '五官' },
  // 10 其他
  { id: 111, condition: '戒烟', acupoints: '列缺透阳溪、筑宾、合谷、肺俞', category: '其他' },
  { id: 112, condition: '盗汗', acupoints: '神门透阴郄、内关', category: '其他' },
  { id: 113, condition: '狐臭', acupoints: '肩髃透极泉', category: '其他' },
  { id: 114, condition: '疟疾', acupoints: '外关透内关、大椎、命门', category: '其他' },
  { id: 115, condition: '中暑昏厥', acupoints: '水沟透龈交、十宣放血', category: '其他' },
  { id: 116, condition: '皮肤痒', acupoints: '三间透合谷、筑宾、至阴、曲池、血海', category: '其他' },
  { id: 117, condition: '脚跟痛', acupoints: '大陵透足根点、承山、仆参、水泉', category: '其他' },
  { id: 118, condition: '静脉曲张', acupoints: '三阴交、足三里、承山、委中', category: '其他' },
  { id: 119, condition: '发烧', acupoints: '大椎、曲池、合谷、外关', category: '其他' },
  { id: 120, condition: '感冒', acupoints: '风池、风府、大椎、合谷', category: '其他' },
];

// ─── 31条透针透穴法 ────────────────────────────────────────
const TRANS_NEEDLING= [
  { id: 1, combo: '中府透云门', indication: '咳嗽、气喘、哮喘、肺癌', supporting: '孔最、公孙、内关', source: '倪海厦' },
  { id: 2, combo: '阳陵泉透阴陵泉', indication: '中风、中经络、雷诺氏病', supporting: '内关、水沟、三阴交、极泉', source: '孙培荣/周左宇/倪海厦' },
  { id: 3, combo: '悬钟透三阴交', indication: '中风、肩膀痛、上肢神经痛', supporting: '阳陵泉', source: '孙培荣/周左宇/倪海厦' },
  { id: 4, combo: '曲池透少海', indication: '半身不遂、偏瘫', supporting: '先针健侧泻法再针患侧补法', source: '孙培荣' },
  { id: 5, combo: '水沟透龈交', indication: '晕倒、晕厥', supporting: '涌泉、关元、丰隆', source: '周左宇' },
  { id: 6, combo: '四神聪透百会', indication: '痴呆', supporting: '印堂、神庭、上星、风池', source: '孙培荣' },
  { id: 7, combo: '神庭透上星', indication: '脑瘫、智力低下', supporting: '四神聪、百会、印堂、风池', source: '孙培荣' },
  { id: 8, combo: '液门透中渚', indication: '臂丛神经痛', supporting: '三间', source: '孙培荣' },
  { id: 9, combo: '合谷透劳宫', indication: '雷诺氏病', supporting: '内关、太渊、阴陵泉、阳陵泉', source: '孙培荣' },
  { id: 10, combo: '条口透承山', indication: '肩膀诸痛', supporting: '阳陵泉、曲垣、肩井', source: '孙培荣/周左宇/倪海厦' },
  { id: 11, combo: '悬钟透三阴交+天髎透曲垣', indication: '肩胛痛、膏肓痛', supporting: '郄门、曲池、肩井、足三里', source: '孙培荣/周左宇/倪海厦' },
  { id: 12, combo: '养老透间使', indication: '臂痛、肘痛', supporting: '液门、中渚、曲池', source: '孙培荣/周左宇/倪海厦' },
  { id: 13, combo: '陷谷透涌泉', indication: '手痛诸证', supporting: '小海、外关、合谷', source: '倪海厦' },
  { id: 14, combo: '三间透劳宫', indication: '手痛、手胀、手木、手麻', supporting: '曲池、肩井、外关', source: '倪海厦' },
  { id: 15, combo: '合谷透劳宫/三间透后溪', indication: '手指痛', source: '倪海厦' },
  { id: 16, combo: '膝阳关透曲泉', indication: '膝盖诸疾', supporting: '风市、阴市', source: '孙培荣' },
  { id: 17, combo: '商丘透丘墟', indication: '脚扭伤', source: '倪海厦' },
  { id: 18, combo: '大陵透足根点', indication: '脚跟痛', supporting: '承山、仆参、水泉', source: '孙培荣' },
  { id: 19, combo: '膝阳关透曲泉', indication: '曲池少海部位不适', source: '孙培荣/周左宇' },
  { id: 20, combo: '三间透合谷', indication: '皮肤痒', supporting: '筑宾、至阴、屋翳、内庭、曲池、血海', source: '孙培荣' },
  { id: 21, combo: '阳白透鱼腰+丝竹空透太阳+地仓透颊车', indication: '面瘫、口眼歪斜', supporting: '先健后患', source: '孙培荣/周左宇/倪海厦' },
  { id: 22, combo: '阳白透鱼腰', indication: '白内障、近视眼', supporting: '睛明、球后、承泣、养老、翳风、丘墟', source: '倪海厦' },
  { id: 23, combo: '太阳透率谷', indication: '偏头痛', supporting: '对侧合谷麻醉、丝竹空放血、然谷', source: '孙培荣' },
  { id: 24, combo: '陷谷透涌泉', indication: '百会痛（头顶痛）', source: '孙培荣' },
  { id: 25, combo: '臂臑透肩髃', indication: '色盲、视神经萎缩', supporting: '复溜、睛明、丝竹空、光明', source: '孙培荣/周左宇' },
  { id: 26, combo: '攒竹透鱼腰/丝竹空透鱼腰', indication: '眼睛不闭、眉棱骨痛', supporting: '阳陵泉', source: '孙培荣' },
  { id: 27, combo: '液门透中渚', indication: '耳鸣', supporting: '翳风、耳门、听会、肾俞', source: '周左宇' },
  { id: 28, combo: '列缺透阳溪', indication: '戒烟', supporting: '筑宾、合谷、肺俞', source: '孙培荣' },
  { id: 29, combo: '神门透阴郄', indication: '盗汗、手汗', supporting: '内关、手五里、间使', source: '周左宇' },
  { id: 30, combo: '外关透内关', indication: '疟疾', supporting: '大椎、命门、委中', source: '孙培荣' },
  { id: 31, combo: '肩髃透极泉', indication: '狐臭', source: '倪海厦' },
];

// ─── 汉唐100方完整列表 ────────────────────────────────────
const HANTANG_FORMULAS= [
  { id: 1, name: '白带丸', indication: '女性赤白带过多', theory: '乳汁下行变化为月经，肝经主疏泄' },
  { id: 2, name: '退乳丸', indication: '退乳汁，预防乳癌', theory: '乳汁与月经同源' },
  { id: 3, name: '补髓丹', indication: '记忆力减退、老年痴呆', theory: '脑为髓海，髓源于肾精', ingredients: '杜仲、补骨脂、鹿茸、没药、核桃肉' },
  { id: 4, name: '皮肤过敏丸', indication: '食物过敏引起皮肤红疹瘙痒', theory: '脾胃功能不足致过敏' },
  { id: 5, name: '通乳丸', indication: '乳汁不足、乳房硬块', theory: '加强心脏热能使乳汁下行', ingredients: '附子、生姜、柴胡、黄芩、桂枝、半夏' },
  { id: 6, name: '手抖心颤方', indication: '手抖、心颤、心脏病早期', theory: '心火不足致心脏压缩力不衡', ingredients: '半夏、桂枝、黄连、白术' },
  { id: 7, name: '胃痈方', indication: '胃痈及胃出血', theory: '血不归经则出血' },
  { id: 8, name: '子宫症痼方', indication: '子宫肌瘤、子宫肿瘤', theory: '加强心脏热能使瘀血排出', ingredients: '桂枝、茯苓、丹皮、白芍' },
  { id: 9, name: '血箭痔丸', indication: '大便前出血如箭射', theory: '小肠湿热下注', ingredients: '百草霜、栀子花、榴花、地榆' },
  { id: 10, name: '大禹丸', indication: '肝癌末期腹腔积水', theory: '大禹治水排腹水', ingredients: '十枣汤加减' },
  { id: 11, name: '代抵当丸', indication: '子宫干血、膀胱蓄血', theory: '破血活血排除瘀血', ingredients: '水蛭、虻虫、桃仁、大黄' },
  { id: 12, name: '脱肛丸', indication: '脱肛、肛门下坠', theory: '中气下陷致直肠脱垂' },
  { id: 13, name: '淋痛方', indication: '小便刺痛、淋症', theory: '相火外泄、热结下焦' },
  { id: 14, name: '胆石方', indication: '胆结石、胆囊息肉', theory: '肝气郁滞、胆汁排泄不利' },
  { id: 15, name: '真寒假热方', indication: '血癌、白血病', theory: '阳气过亢、阴液不足' },
  { id: 16, name: '干痒癣方', indication: '皮肤干燥、牛皮癣', theory: '肺主皮毛，强化肺津液输布' },
  { id: 17, name: '湿疹脓疮方', indication: '皮肤湿疹、黄水疮', theory: '脾运化不足致脾湿肠燥' },
  { id: 18, name: '蛇方', indication: '带状疱疹', theory: '经络不通、火气上逆' },
  { id: 19, name: '焦虑方', indication: '气血两虚型焦虑抑郁', theory: '肺主气心主血不足' },
  { id: 20, name: '四肢无力方', indication: '下肢无力、肌肉萎缩', theory: '脾运化功能不足' },
  { id: 21, name: '补阳还五丸', indication: '中风后遗症、瘫痪', theory: '气虚血瘀阻滞脑部' },
  { id: 22, name: '奔豚汤', indication: '奔豚气、腹部动悸', theory: '浊气上冲、气机错乱' },
  { id: 23, name: '降压方', indication: '高血压、中风预防', theory: '肝升肺敛失衡', ingredients: '桔梗、五味子、桃仁、丹皮' },
  { id: 24, name: '消渴方', indication: '糖尿病、消渴症', theory: '脾运化不足致血糖失常', ingredients: '山茱萸、生地、石膏' },
  { id: 25, name: '疏通经络剂', indication: '三叉神经痛', theory: '经络不通、火气上逆' },
  { id: 26, name: '石淋方', indication: '肾结石、尿路结石', theory: '肝郁相火煎熬水液成石' },
  { id: 27, name: '痛风丸', indication: '痛风、关节红肿剧痛', theory: '郁则生风、毒气积聚关节' },
  { id: 28, name: '风湿丸', indication: '风湿性关节炎', theory: '风寒湿三邪痰饮停留关节' },
  { id: 29, name: '消痔丸', indication: '外痔疮、肛门痛痒', theory: '升气血解毒' },
  { id: 30, name: '坐骨神经痛方', indication: '坐骨神经痛、腰痛', theory: '经络堵塞、椎间盘突出压迫' },
  { id: 31, name: '三酸甘油脂方', indication: '三酸甘油脂过高', theory: '中焦湿热过盛' },
  { id: 32, name: '乌金丸', indication: '心痛澈背、背痛澈心', theory: '心脏病前兆' },
  { id: 33, name: '湿热便秘方', indication: '中焦湿热兼便秘', theory: '湿热壅结大肠' },
  { id: 34, name: '补天丸', indication: '掉头发、耳鸣', theory: '肾精不足' },
  { id: 35, name: '紫金丹', indication: '胸腔内伤、上身瘀血', theory: '活血化瘀' },
  { id: 36, name: '天青丸', indication: '妇女痛经、下身瘀血', theory: '增加小肠热量促进静脉回流' },
  { id: 37, name: '天威丸', indication: '男性精子不足', theory: '补肾壮精' },
  { id: 38, name: '玉华丸', indication: '女性滋补', theory: '滋补阴液' },
  { id: 39, name: '鼻渊丸', indication: '鼻塞不通、流清涕', theory: '温肺通窍' },
  { id: 40, name: '乌梅丸', indication: '各种寄生虫、蛔虫', theory: '驱虫安蛔' },
  { id: 41, name: '中安丸', indication: '失眠', theory: '交通心肾' },
  { id: 42, name: '控涎丹', indication: '痰阻塞胸肺、癫痫', theory: '攻逐痰饮' },
  { id: 43, name: '麻子仁丸', indication: '大便如羊屎小颗粒', theory: '润肠通便' },
  { id: 44, name: '皂荚丸', indication: '清除肺中吸烟浊痰', theory: '涤痰清肺' },
  { id: 45, name: '己椒苈黄丸', indication: '右腹胀、肠间水气', theory: '分消湿热水饮' },
  { id: 46, name: '六味地黄丸', indication: '滋阴补肾通用', theory: '三补三泻' },
  { id: 47, name: '重阳丸', indication: '男子精中带血', theory: '固肾清相火' },
  { id: 48, name: '金匮肾气丸', indication: '手脚冰冷、强化肾脏', theory: '补肾助阳' },
  { id: 49, name: '起阳丸', indication: '振奋阳气、增强性功能', theory: '生精壮阳' },
  { id: 50, name: '牙痛止痛剂', indication: '牙痛', theory: '清热止痛' },
  { id: 52, name: '赤丸', indication: '心脏肥大、动脉剥离', theory: '心阳不足致心脏代偿肥大', ingredients: '半夏、枳实、炙甘草' },
  { id: 53, name: '风引汤', indication: '风痱（中风后四肢无力）', theory: '排出骨节深层风寒湿' },
  { id: 54, name: '喉蛾方', indication: '扁桃腺发炎', theory: '相火不收藏冲击咽喉' },
  { id: 55, name: '紫云膏', indication: '皮肤生坚结（外用）', theory: '活血化瘀外用' },
  { id: 56, name: '汉唐红', indication: '外用伤口特效药', theory: '活血生肌' },
  { id: 57, name: '佛州黑', indication: '外用烫伤特效药', theory: '清热生肌' },
  { id: 58, name: '白内障药水', indication: '白内障（外用）', theory: '外用通窍明目' },
  { id: 59, name: '喷鼻药粉', indication: '鼻炎过敏、昏迷急救', theory: '开脑窍刺激鼻窦' },
  { id: 60, name: '强力天青丸', indication: '双足静脉曲张', theory: '增强小肠热量促进静脉回流' },
  { id: 61, name: '明目地黄丸', indication: '眼睛保养、视力不足', theory: '肝开窍在眼、补肝明目' },
  { id: 62, name: '沉香桂附丸', indication: '少腹痛、下利、双足冷', theory: '沉香引火归元温肾气' },
  { id: 63, name: '骨损方', indication: '骨质疏松症', theory: '肾主骨、补肾强骨' },
  { id: 64, name: '更年期方', indication: '经停后身热盗汗', theory: '子宫萎缩热能回逆三焦' },
  { id: 65, name: '膀胱结石方', indication: '膀胱结石、尿道炎', theory: '清利湿热' },
  { id: 66, name: '前列腺方', indication: '前列腺肥大、膀胱无力', theory: '增强膀胱气化功能' },
  { id: 67, name: '失心丸', indication: '癫痫发狂', theory: '阴乔阳乔失衡、清肺痰' },
  { id: 68, name: '护肝丸', indication: '乙肝及各类肝病', theory: '见肝之病知肝传脾当先实脾' },
  { id: 69, name: '肾积水方', indication: '肾积水、下肢水肿', theory: '恢复肾脏排尿功能' },
  { id: 70, name: '定心丸', indication: '心肾不交、焦虑忧郁', theory: '心火下行肾水上升' },
  { id: 71, name: '清郁开结丸', indication: '强烈沮丧、忧郁感', theory: '肝郁脾结开郁升肝木' },
  { id: 72, name: '浮萍方', indication: '小儿风痒、皮肤病', theory: '浮萍辛凉利湿止痒' },
  { id: 73, name: '透脓方', indication: '四肢末梢坏疽', theory: '增加小肠热力驱邪生肌' },
  { id: 74, name: '搜风解毒汤', indication: '性病泡疹淋病梅毒', theory: '清除病毒由小便排出' },
  { id: 75, name: '枕中丹', indication: '令人聪明', theory: '补脑益智' },
  { id: 76, name: '避孕丸', indication: '避孕', theory: '中药避孕' },
  { id: 77, name: '心绞痛方', indication: '心脏动脉阻塞', theory: '清肝毒排血管瘀物' },
  { id: 78, name: '健胃散', indication: '各种胃病', theory: '温降调理胃气' },
  { id: 79, name: '青春痘方', indication: '青春痘', theory: '相火旺盛排毒表现' },
  { id: 80, name: '减肥丸', indication: '过胖症', theory: '心脏是唯一控制体重的脏器' },
  { id: 81, name: '鼻过敏头痛方', indication: '鼻过敏合并头痛', theory: '鼻窍堵塞阻断气血', ingredients: '白附子、僵蚕' },
  { id: 82, name: '下焦寒实方', indication: '前列腺癌', theory: '导引心热下行至小肠', ingredients: '炮附、细辛、五味子、丹皮、木通、桂枝' },
  { id: 83, name: '皮肤诸病粉', indication: '皮肤生疮化脓（外用）', theory: '去湿化脓生新皮', ingredients: '密陀僧、雄黄' },
  { id: 84, name: '肝结石方', indication: '胆切除后肝结石', theory: '失去胆吸力致胆汁积滞', ingredients: '柴胡、枳实、黄芩、郁金、海金沙' },
  { id: 85, name: '青春痘外用粉', indication: '青春痘（外用）', theory: '滋润清炎' },
  { id: 86, name: '脚气方', indication: '脚气病香港脚（外用）', theory: '杀菌除湿' },
  { id: 87, name: '心脏肥大方', indication: '心脏肥大症', theory: '心阳不足代偿性变化' },
  { id: 88, name: '磁珠丸', indication: '白内障、青光眼', theory: '磁石收纳肾气交通心肾', ingredients: '磁石、决明子、神曲' },
  { id: 89, name: '健筋骨丸', indication: '骨折、肌肉萎缩、坐骨神经痛', theory: '肝主筋肾主骨乙癸同源' },
  { id: 90, name: '消瘤丸', indication: '甲状腺肿瘤（大脖子）', theory: '阳气行则阴不积' },
  { id: 92, name: '增高丸', indication: '身材矮小', theory: '补肾精同时收敛阴成形' },
  { id: 93, name: '小儿过动症方', indication: '多动症ADHD', theory: '心火上炎肾水不济', ingredients: '木通、附子' },
  { id: 95, name: '拖里化毒饮', indication: '淋巴脓块、乳房脓块', theory: '里拖毒外拔毒相结合' },
  { id: 96, name: '乳癌外用粉', indication: '乳癌脓块（外用）', theory: '外用拔毒' },
  { id: 97, name: '何首乌丸', indication: '白发、延年益寿', theory: '何首乌补肝血养精气' },
  { id: 98, name: '五石乌头丸', indication: '严重癌症、严重风湿', theory: '金石丹药攻力猛', ingredients: '钟乳、硫磺、矾石、紫石英、赤石脂、乌头、附子等32味' },
  { id: 99, name: '斑龙丸', indication: '脑受损、肾阴阳两虚', theory: '鹿角鹿茸补厥下海底阴' },
  { id: 100, name: '历节丸', indication: '类风湿性关节炎', theory: '源自金匮乌头汤症', ingredients: '生乌头' },
];

// ─── 核心经方精选（伤寒论+金匮要略） ──────────────────────
const CLASSIC_FORMULAS= [
  { id: 'cf-01', name: '桂枝汤', source: '伤寒论', composition: '桂枝10g、白芍10g、生姜二片、炙甘草10g、红枣十枚', indication: '太阳中风，调和营卫', niUsage: '太阳中风第一方，脉浮缓有汗恶风' },
  { id: 'cf-02', name: '麻黄汤', source: '伤寒论', composition: '麻黄9g、桂枝6g、杏仁9g、炙甘草3g', indication: '太阳伤寒，发汗解表', niUsage: '脉浮紧无汗恶寒身疼' },
  { id: 'cf-03', name: '小柴胡汤', source: '伤寒论', composition: '柴胡24g、黄芩9g、半夏9g、生姜9g、人参9g、甘草6g、大枣12枚', indication: '和解少阳', niUsage: '往来寒热胸胁苦满' },
  { id: 'cf-04', name: '白虎汤', source: '伤寒论', composition: '石膏50g、知母18g、甘草6g、粳米一合', indication: '清阳明里热', niUsage: '壮热汗出大渴大烦' },
  { id: 'cf-05', name: '四逆汤', source: '伤寒论', composition: '附子一枚、干姜9g、炙甘草6g', indication: '回阳救逆', niUsage: '少阴寒化主方，四肢厥冷脉微细' },
  { id: 'cf-06', name: '小青龙汤', source: '伤寒论', composition: '麻黄12g、芍药9g、干姜9g、半夏9g、桂枝6g、炙甘草6g、细辛3g、五味子3g', indication: '表寒里寒伴水饮', niUsage: '外寒内饮咳喘痰多清稀' },
  { id: 'cf-07', name: '大青龙汤', source: '伤寒论', composition: '麻黄12g、桂枝6g、杏仁6g、石膏如鸡蛋大、甘草6g、生姜9g、大枣12枚', indication: '表实里热', niUsage: '恶寒无汗烦躁' },
  { id: 'cf-08', name: '葛根汤', source: '伤寒论', composition: '葛根12g、麻黄9g、桂枝6g、芍药6g、甘草6g、生姜9g、大枣12枚', indication: '太阳阳明合病项背强', niUsage: '项背强几几、下利' },
  { id: 'cf-09', name: '真武汤', source: '伤寒论', composition: '附子一枚、茯苓9g、白术6g、芍药9g、生姜9g', indication: '阳虚水泛', niUsage: '心下悸、头眩、身瞤动' },
  { id: 'cf-10', name: '理中汤', source: '伤寒论', composition: '人参9g、白术9g、干姜9g、甘草9g', indication: '中焦虚寒', niUsage: '腹痛吐利、四肢不温' },
  { id: 'cf-11', name: '苓桂术甘汤', source: '金匮', composition: '茯苓12g、桂枝9g、白术6g、甘草6g', indication: '痰饮病基础方', niUsage: '心下逆满气上冲胸头眩' },
  { id: 'cf-12', name: '五苓散', source: '伤寒论', composition: '猪苓9g、泽泻15g、茯苓9g、白术9g、桂枝6g', indication: '水气病', niUsage: '小便不利、渴欲饮水' },
  { id: 'cf-13', name: '桂枝加葛根汤', source: '伤寒论', composition: '桂枝汤加葛根12g', indication: '太阳中风项背强', niUsage: '项背强几几有汗' },
  { id: 'cf-14', name: '桂枝加厚朴杏仁汤', source: '伤寒论', composition: '桂枝汤加厚朴、杏仁', indication: '表证兼咳喘', niUsage: '太阳中风兼喘' },
  { id: 'cf-15', name: '麻杏甘石汤', source: '伤寒论', composition: '麻黄6g、杏仁9g、甘草6g、石膏24g', indication: '发汗后咳喘热盛', niUsage: '汗出而喘' },
  { id: 'cf-16', name: '大承气汤', source: '伤寒论', composition: '大黄12g、芒硝9g、厚朴15g、枳实12g', indication: '阳明腑实证', niUsage: '痞满燥实四证俱全' },
  { id: 'cf-17', name: '小承气汤', source: '伤寒论', composition: '大黄12g、厚朴6g、枳实9g', indication: '阳明腑实轻证', niUsage: '痞满不燥实' },
  { id: 'cf-18', name: '当归四逆汤', source: '伤寒论', composition: '当归9g、桂枝9g、芍药9g、细辛3g、通草6g、甘草6g、大枣25枚', indication: '血虚寒凝手足厥冷', niUsage: '手足厥寒、脉细欲绝' },
  { id: 'cf-19', name: '乌梅丸', source: '伤寒论', composition: '乌梅30枚、细辛6g、干姜10g、黄连9g、当归4g、附子6g、蜀椒4g、桂枝6g、人参6g、黄柏6g', indication: '厥阴病寒热错杂蛔厥', niUsage: '消渴气上撞心饥而不欲食' },
  { id: 'cf-20', name: '炙甘草汤', source: '伤寒论', composition: '炙甘草12g、生姜9g、人参6g、生地黄48g、桂枝9g、阿胶6g、麦冬12g、麻仁12g、大枣30枚', indication: '心动悸脉结代', niUsage: '气血不足心律不齐' },
  { id: 'cf-21', name: '肾气丸', source: '金匮', composition: '干地黄24g、山药12g、山茱萸12g、泽泻9g、茯苓9g、丹皮9g、桂枝3g、炮附子3g', indication: '肾阳不足', niUsage: '腰痛脚软小便不利' },
  { id: 'cf-22', name: '桂枝茯苓丸', source: '金匮', composition: '桂枝、茯苓、丹皮、桃仁、芍药各等分', indication: '瘀血阻滞胞宫', niUsage: '妊娠下血不止、子宫肌瘤' },
  { id: 'cf-23', name: '温经汤', source: '金匮', composition: '吴茱萸9g、当归6g、芍药6g、川芎6g、人参6g、桂枝6g、阿胶6g、丹皮6g、生姜6g、甘草6g、半夏6g、麦冬9g', indication: '冲任虚寒瘀血阻滞', niUsage: '妇人少腹寒、久不受胎' },
  { id: 'cf-24', name: '防己黄芪汤', source: '金匮', composition: '防己12g、黄芪15g、白术9g、甘草6g、生姜4片、大枣1枚', indication: '风水、风湿表虚', niUsage: '汗出恶风身重小便不利' },
  { id: 'cf-25', name: '小建中汤', source: '伤寒论', composition: '桂枝9g、芍药18g、甘草6g、生姜9g、大枣12枚、饴糖30g', indication: '中焦虚寒腹痛', niUsage: '腹中急痛、虚劳' },
];

// ─── 统计 ────────────────────────────────────────────────
const RENJI_STATS = {
  totalModules: RENJI_MODULES.length,
  totalChapters: RENJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  totalLessons: '150+集',
  completionYear: '2004-2005',
  learningOrder: ['针灸大成', '黄帝内经', '神农本草经', '伤寒论', '金匮要略'],
  acuExperienceCount: 215,
  transNeedlingCount: 31,
  hantangFormulaCount: 100,
  classicFormulaCount: 259,
};

/**
 * 地纪 — 倪海厦地理风水体系数据库
 *
 * 「下知地理」—— 地之纪，是地理志的体系化研究。
 * 倪海厦原计划60岁后著述，利用天文地理知识与医学素养
 * 重新编写各国地理志，研究国家人性、物产与其风水地理的关系。
 *
 * 倪师于2012年辞世，地纪未能完成，为「倪师未竟之业」。
 * 现有内容来自天纪课程中的堪舆学部分以及后人整理的遗稿。
 */

// ─── 地纪模块 ────────────────────────────────────────────
const DIJI_MODULES= [
  {
    id: 'dj-guojiadili',
    category: 'diji',
    name: '国家地理志',
    nameEn: 'National Geography',
    subtitle: '倪师未竟之业 · 遗稿研读',
    description: '倪师计划以风水地理知识解读各国地理环境对国民性格、物产资源、国运兴衰的影响。这是倪师未能完成的宏愿。',
    details: [
      '地纪是倪海厦三大著作体系中最后计划完成的部分，原定60岁后开始著述。',
      '核心设想是用风水地理知识重新编写各国地理志，将传统堪舆学应用于宏观国家层面。',
      '研究方向包括：国家的地理位置、山川河流对国民性格的塑造，物产资源与风水格局的关系，历史兴衰与地理变迁的关联。',
      '倪师于2012年辞世，地纪仅留下初步构想和天纪课程中堪舆学的理论基础。这些宝贵的思想火花值得后辈整理和传承。',
    ],
    references: [
      '倪海厦《天纪》堪舆学部分',
      '倪海厦讲课中的地理志构想',
    ],
    keywords: ['地纪', '国家地理', '风水', '地理志', '国运', '物产', '人性', '堪舆'],
    icon: '⊞',
    status: 'preview',
    order: 1,
    slug: 'geography',
    chapters: [
      {
        id: 'dj-dl-01',
        title: '地纪构想',
        subtitle: '倪师的宏愿与蓝图',
        description: '倪师对地纪的整体构想——用风水地理知识解读国家命运。',
        keyPoints: [
          '计划60岁后著述（倪师生于1954年）',
          '融合天文地理知识与医学素养',
          '重新编写各国地理志',
          '研究人性、物产与风水地理的关系',
        ],
        quotes: ['我想在六十岁以后，利用我的天文地理知识与医学素养来重新写过地理志'],
        order: 1,
      },
      {
        id: 'dj-dl-02',
        title: '地理与人性',
        subtitle: '一方水土养一方人',
        description: '不同地理环境如何塑造不同的民族性格和文化特征。',
        keyPoints: [
          '山地民族与平原民族的性格差异',
          '水系分布对农业文明的影响',
          '气候带与人的体质、性格的关系',
          '风水好的地方必有贤人出',
        ],
        order: 2,
      },
    ],
  },
  {
    id: 'dj-kanyu-theory',
    category: 'diji',
    name: '堪舆理论基础',
    nameEn: 'Feng Shui Theory',
    subtitle: '天纪堪舆学 · 理论整理',
    description: '整理自天纪课程中的堪舆学理论部分，作为地纪的理论基础。包括峦头学、理气学、阳宅学等核心理论。',
    details: [
      '虽然地纪未能独立成书，但天纪课程中已包含丰富的堪舆学理论内容。',
      '这些理论是地纪的基础框架，涵盖了从微观（住宅）到宏观（城市、国家）的风水分析方法。',
      '倪师采用九星派（杨救贫流派），注重峦头与理气并重。',
      '这部分内容可以看作是地纪的「理论预科」，为后续的国家地理志研究提供方法论。',
    ],
    school: '九星派（杨救贫流派）',
    references: [
      '倪海厦《天纪·地脉道》',
      '杨救贫风水典籍',
    ],
    keywords: ['堪舆', '风水理论', '峦头', '理气', '九星派', '杨救贫', '阳宅', '阴宅'],
    icon: '◫',
    status: 'active',
    order: 2,
    slug: 'kanyu-theory',
    chapters: [
      {
        id: 'dj-kt-01',
        title: '峦头学',
        subtitle: '山形水势的判断',
        description: '通过观察山的形状、走向、水的流向等自然地貌来判断风水吉凶。',
        keyPoints: [
          '龙脉：山脉的走势与气脉',
          '穴位：藏风聚气的最佳位置',
          '砂手：穴位左右的山势环抱',
          '水口：水流的进出方位',
        ],
        order: 1,
      },
      {
        id: 'dj-kt-02',
        title: '理气学',
        subtitle: '方位吉凶的推算',
        description: '通过罗盘测量方位，结合九星飞布、八煞黄泉等理论推算吉凶。',
        keyPoints: [
          '罗盘的使用方法',
          '九星飞布的原理',
          '八煞黄泉的禁忌方位',
          '三吉六秀的吉利方位',
        ],
        order: 2,
      },
      {
        id: 'dj-kt-03',
        title: '阳宅应用',
        subtitle: '居住环境的风水实践',
        description: '将堪舆理论应用于住宅选择和布局的实际操作方法。',
        keyPoints: [
          '房屋坐向的选择原则',
          '室内功能区的方位安排',
          '周围环境的吉凶判断',
          '化解不良风水的方法',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'dj-yigao',
    category: 'diji',
    name: '遗稿与后学',
    nameEn: 'Legacy & Continuation',
    subtitle: '后辈补注 · 薪火相传',
    description: '整理倪师关于地纪的零散讲述、后辈学生的研究补注，以及地纪思想的现代延伸。',
    details: [
      '倪师虽未完成地纪专著，但在天纪课程和其他场合多次提及地纪的构想和要点。',
      '后辈学生和研究者根据倪师的讲述和遗稿，进行了一定程度的整理和补注。',
      '地纪的思想在现代风水研究、城市规划、环境科学等领域有着重要的参考价值。',
      '本模块旨在收集、整理与地纪相关的所有散见材料，为后续研究提供基础。',
    ],
    references: [
      '倪海厦讲课实录',
      '后辈学生笔记与研究',
    ],
    keywords: ['遗稿', '后学', '补注', '传承', '现代应用'],
    icon: '⊟',
    status: 'coming',
    order: 3,
    slug: 'legacy',
    chapters: [
      {
        id: 'dj-yg-01',
        title: '倪师地纪语录',
        subtitle: '散见于各课程的地纪思想',
        description: '从天纪、人纪等课程中摘录倪师关于地纪的重要论述。',
        keyPoints: [
          '地纪的创作动机与规划',
          '对各国地理环境的观察',
          '风水与国运的关系论述',
          '地纪与天纪、人纪的关联',
        ],
        quotes: [
          '人事的努力加上地理上的调整，一定能大于先天的命运',
          '2/3大于1/3——人事+地理=2/3，先天命运=1/3',
        ],
        order: 1,
      },
    ],
  },
];

// ─── 统计 ────────────────────────────────────────────────
const DIJI_STATS = {
  totalModules: DIJI_MODULES.length,
  totalChapters: DIJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  status: '倪师未竟之业 · 后辈持续整理中',
  note: '倪海厦原计划60岁后著述地纪，2012年辞世，地纪仅留下构想和理论基础',
};

/**
 * 倪海厦 天纪 / 地纪 / 人纪 — 统一导出
 *
 * 倪海厦（1954-2012），美国汉唐中医学院创办人，
 * 当代少见的「命、相、卜、山、医」五术兼备之旷世奇人。
 *
 * 三纪体系：
 *   天纪 —— 上知天文（紫微斗数、易经、堪舆、推命、面相、测字）
 *   地纪 —— 下知地理（国家地理志、风水与国运）
 *   人纪 —— 中知人事（针灸、黄帝内经、神农本草经、伤寒论、金匮要略）
 */



/** 倪海厦完整传记 */
const NI_HAIXIA_BIO = {
  name: '倪海厦',
  nameVariant: '倪海夏',
  alias: '梵宇龙',
  birth: '1954年1月1日',
  death: '2012年1月31日',
  birthPlace: '台北市',
  ancestry: '浙江瑞安',
  family: '七个兄弟姊妹，排行第五',
  education: '东吴大学政治系',
  title: '美国汉唐中医学院创办人',
  titles: [
    '命、相、卜、山、医 五术兼备之旷世奇人',
    '美国汉唐中医学院院长',
    '美国加州中医药大学博士指导教授',
    '佛罗里达州卫生署中医委员会最高委员（2000-2003）',
    '佛州针灸委员会委员及副主席',
    '经方派现代继承者',
    '天纪、人纪教学体系创立者',
    '海外优秀华人奖获得者',
  ],
  /** 师承关系 */
  teachers: [
    { name: '周左宇', background: '北京四代家传名医，1949年后移居台湾', subject: '针灸', period: '1977-1981' },
    { name: '徐济民', background: '江苏籍上海名医', subject: '针灸', period: '1970s' },
    { name: '姜佐景传承', background: '师承曹颖甫的经方家', subject: '经方', period: '基隆中药行学徒期间' },
  ],
  /** 核心理念 */
  corePhilosophy: [
    '大道至简——飞星飞来飞去太复杂，不搞这个',
    '命宫为本，三方为用',
    '人事努力+地理调整 > 先天命运（2/3 > 1/3）',
    '中医是物理医学，从物理角度分析人体',
    '辨证不辨病——中医看的是证型而非病名',
    '经方一剂知，二剂已',
    '不希望中华文化失传，所以教了许多学生',
    '算命就是一个讨论果的哲学',
    '文字只是船，真理才是彼岸',
  ],
  /** 人生大事记 */
  timeline: [
    { year: '1954', event: '出生于台北市，祖籍浙江瑞安' },
    { year: '1970s', event: '高中时以《医宗金鉴》治愈二姐月经痛，立志习医' },
    { year: '1977-1981', event: '向周左宇医师学习针灸' },
    { year: '1978', event: '军旅服役马祖军医部，获"马祖神医"称号，时年24岁' },
    { year: '1979', event: '退伍后以化名"梵宇龙"开始算命看相事业' },
    { year: '1980', event: '移民美国' },
    { year: '1988', event: '在台北金山南路开办"天文地理班"，传授紫微斗数和阳宅风水' },
    { year: '1991', event: '成为美国佛罗里达州注册针灸师' },
    { year: '1993', event: '在佛州Merritt Island选定汉唐中医学院地产' },
    { year: '1994', event: '完成《天纪》系列著作录制，共24集' },
    { year: '1995', event: '创办汉唐中医学院' },
    { year: '2000-2003', event: '任佛州卫生署中医委员会最高委员' },
    { year: '2004', event: '在台北开设《人纪》中医教学班' },
    { year: '2005', event: '《人纪》系列教学DVD出版' },
    { year: '2007', event: '开始撰写《地纪》' },
    { year: '2010', event: '成立台北汉唐经方中医诊所；受邀第三届扶阳论坛整天演讲' },
    { year: '2011', event: '成立深圳汉唐经方中医馆' },
    { year: '2012', event: '1月31日因心肺衰竭在台北辞世，享年59岁' },
  ],
  /** 著作体系 */
  publications: {
    originalBooks8: ['黄帝内经素问', '黄帝内经', '神农本草经', '针灸', '伤寒论', '金匮', '人间道', '天机道·地脉道'],
    totalBooks: '26-44册（含注解版教材、医案全集、穴位精解等）',
    hantangFormulas: '汉唐100方',
    classicFormulas: '259个经典配方',
    medicalCases: '医案全集7本',
    totalVideoHours: '200+小时',
  },
  /** 三纪体系 */
  sanJi: {
    tianji: {
      name: '天纪',
      meaning: '上知天文',
      content: '紫微斗数、易经64卦、堪舆学、推命学、面相学、测字术',
      recordYear: 1994,
      episodes: 24,
      hdEpisodes: 83,
      hoursPerEpisode: 2,
      totalHours: 48,
      books: ['天机道', '人间道', '地脉道', '64卦易图'],
      schools: ['三合派（紫微斗数）', '象数派（易经）', '九星派（堪舆）', '河洛数理派（推命）'],
      structure: '前一小时讲命学，后一小时讲易经',
    },
    renji: {
      name: '人纪',
      meaning: '中知人事',
      content: '针灸大成(44集)、黄帝内经(20集)、神农本草经(46集)、伤寒论、金匮要略(20集)',
      completionYear: '2004-2005',
      totalLessons: '150+集',
      learningOrder: '针灸→黄帝内经→神农本草经→伤寒论→金匮要略',
      acuExperience: 215,
      transNeedling: 31,
      hantangFormulas: 100,
    },
    diji: {
      name: '地纪',
      meaning: '下知地理',
      content: '国家地理志（未完成）',
      status: '倪师未竟之业',
      note: '原计划60岁后著述，2012年辞世',
      startYear: 2007,
      existingContent: '天纪课程中堪舆学部分 + 后人整理遗稿',
    },
  },
  /** 人格特征 */
  personality: {
    算命风格: '铁口直断不留余地',
    音乐爱好: '最喜老鹰乐队《加州旅馆》',
    生活技能: '做饭洗衣样样精通，一手面点功夫人人喊赞',
    工作态度: '床头经年放纸笔，遭遇疑难杂症时向先师祝祷',
    睡眠: '多年夜间睡眠不足三小时',
    患者评价: '常被美国病患称为"最后的希望（The last hope）"',
  },
  /** 传人选拔标准 */
  discipleStandards: [
    '心性好',
    '个性强',
    '主见强',
    '敏锐观察力',
    '勇于批判错误理论',
  ],
};

/** 三纪导航 */
const SANJI_CATEGORIES = [
  { key: 'tianji', name: '天纪', nameEn: 'Tian Ji', icon: '⊙', meaning: '上知天文', color: '#d4a843', href: '/tianji' },
  { key: 'diji', name: '地纪', nameEn: 'Di Ji', icon: '⊞', meaning: '下知地理', color: '#6b8a5e', href: '/diji' },
  { key: 'renji', name: '人纪', nameEn: 'Ren Ji', icon: '⊕', meaning: '中知人事', color: '#8b6b9e', href: '/renji' },
];

  window.Ziwei.Nihai = {
    // 天纪
    TIANJI_MODULES: TIANJI_MODULES,
    HEXAGRAMS: HEXAGRAMS,
    FENGSHUI_ENTRIES: FENGSHUI_ENTRIES,
    TIANJI_EPISODES: TIANJI_EPISODES,
    TIANJI_QUOTES: TIANJI_QUOTES,
    TIANJI_STATS: TIANJI_STATS,
    // 人纪
    RENJI_MODULES: RENJI_MODULES,
    ACU_EXPERIENCES: ACU_EXPERIENCES,
    TRANS_NEEDLING: TRANS_NEEDLING,
    HANTANG_FORMULAS: HANTANG_FORMULAS,
    CLASSIC_FORMULAS: CLASSIC_FORMULAS,
    RENJI_STATS: RENJI_STATS,
    // 地纪
    DIJI_MODULES: DIJI_MODULES,
    DIJI_STATS: DIJI_STATS,
    // 传记
    NI_HAIXIA_BIO: NI_HAIXIA_BIO,
    SANJI_CATEGORIES: SANJI_CATEGORIES,
  };
  console.log('[Ziwei] 倪海厦三纪知识库就绪');
})();
